### ISSUE TITLE
RoccoSiffredi..com

### ISSUE THREAD

**Issue by byertsy** [stashapp/CommunityScrapers#1030]
URL icon goes white but nothing loads after clicking.

TIA :)

**Comment by DogmaDragon** [comment]
Do you have Python installed? 

You also need some modules. 

`You need to install the requests module. (https://docs.python-requests.org/en/latest/user/install/)`
`If you have pip (normally installed with python), run this command in a terminal (cmd): pip install requests`
`You need to download the folder 'py_common' from the community repo! (CommunityScrapers/tree/master/scrapers/py_common)`

**Comment by byertsy** [comment]
Thanks for replying. Turns out it was my bad - I was trying to match full movies rather than scenes. 🙄

**Comment by bnkai** [comment]
Issue resolved. Closing....
