### ISSUE TITLE
How to scrape Bang?

### ISSUE THREAD

**Issue by vega69-ux** [stashapp/CommunityScrapers#1054]
I'm very new to scrapers so please forgive me if I sound incompetent. 

I have clicked on the green button code, and downloaded the .zip file on GitHub. "CommunityScrapers-master.zip" file. This is where I get lost. I see the many .yml files and don't know what to do next. I have the recent version of Python installed. I'm using Windows 10 fyi. 

Here is a list of some questions that I have:

- How do I configure and setup

- How do I scrape from Bang? 

- Is it possible to download all the different video resolutions at one go?

- Is it possible to download the .zip pictures files too along with the different video resolutions?

Any help would be appreciated.

**Comment by philpw99** [comment]
If you never used scrapers before, I recommend you using my Stash_Helper. It can help you install/remove regular scrapers easily.
https://github.com/philpw99/Stash_Helper

Once the scraper is installed, you get the URL for that video, like "https://www.bang.com/video/xxxxx", and paste it in the video(scene)'s "URL" field, then you will see the scrape icon next to it lights up (from grey to white). Click on it, and it will retrieve the information for that video.
