### ISSUE TITLE
scarping a url inside a url

### ISSUE THREAD

**Issue by xiosensei** [stashapp/CommunityScrapers#107]
It would be really helpful and I think it will solve some missing scene info problems if we are able to grab a url using xpath, visit that url and grab an html element in there.

Here is a complex scenario just to demonstrate the power of this: 

iafd.com/title.rme/title=horny+vixens/year=2020/horny-vixens.htm

consider the link above. If I can scrape the page, find the letsdoit url which will redirect me to the main page in this case. search for the title scraped from the iafd page and send a post request. then scrape the scene that is needed with all the needed info.

Obviously the example that I provided requires many things other things such as 1 and 2 below:
1) inheritance of the data being scraped (in the example I used the title to demonstrate that)
2) be able to press enter or post a form on a page
3) be able to browse the page posted and scrape it **I think this should be the start to get all the other stuff that I suggested done.** as this represented the title of this issue.

**Comment by bnkai** [comment]
Apart from the `post` that stash doesn't support i think most of what you mention is doable using the `subScraper` post process option ( [wiki](https://github.com/stashapp/stash/wiki/Scraping-configuration ) ). There are some scrapers already using the `subScraper` functionality familytherapy, joymii, bangbros are a just few of them.

**Comment by bnkai** [comment]
Closing due to inactiviy.
If the `subScraper` is not enough make a new request issue in stash instead. This doesnt look like a `CommunityScrapers` issue.
