### ISSUE TITLE
Scraper Suggestion - Club Elegant Angel

### ISSUE THREAD

**Issue by VonTittyslappen** [stashapp/CommunityScrapers#1075]
Hi all

I recommend having a scraper for the old Elegant Angel site called Club Elegant Angel, as I think it's important to have a scraper for this site as you never know when EA (not Electronic Arts lol) will take it down, as they've moved to a new site and URL

Please can someone do the honours and create a scraper? :)

http://www.clubelegantangel.com/home.html

Many Thanks

**Comment by DogmaDragon** [comment]
Added here https://github.com/stashapp/CommunityScrapers/pull/1082

**Comment by VonTittyslappen** [comment]
Thanks so much for doing this @DogmaDragon :)
