### ISSUE TITLE
ThePornDB (metadataapi.net) no longer working?

### ISSUE THREAD

**Issue by eshemm22** [stashapp/CommunityScrapers#1106]
Looks like new UI on metadataapi.net...  Scraping now returns no new data.  After pasting in a link, and hitting scrape, nothing happens.

Any ideas?

**Comment by MRobi1** [comment]
Can confirm this issue

**Comment by DogmaDragon** [comment]
Use the API-based scraper called `ThePornDB.yml`.

**Comment by MRobi1** [comment]
> Use the API-based scraper called `ThePornDB.yml`.

Still getting Error 400's with the updated file.
Using "Scrape With" then selecting ThePornDB
Also using search and selecting ThePornDB

Lastly when entering the direct URL and clicking scrape, I don't get the 400 error but it just does nothing.

I've reloaded scrapers, rebooted stash, and also rebuilt the stash container. No change.

**Comment by MrX292** [comment]
> EDIT: Forgot to add my api key when I updated to the new file. Works using the "scrape with" and the "search" function now. Still does not work when entering the direct URL

it was updated and works now with the normal url
