### ISSUE TITLE
Create a central user config file

### ISSUE THREAD

**Issue by sampulsar** [stashapp/CommunityScrapers#1110]
ThePornBD scraper requires that the file need altering so that the authentication token can be set.

This should move to a central file that the  user can modify, and they can still get the latest version from github automatically without the need to check the file back out, pull the latest and then alter the file again.

There should be one central file for all user defined parameters for the scrapers.

**Comment by Maista6969** [comment]
We recommend using ThePornDB as a stash-box now not only because it means you won't have to update the YAML file with your API key but because it allows for phash matching. The idea of a centralised place for scraper and plugin configuration is a good idea and should be an issue in the stash repo
