### ISSUE TITLE
JavLand.yml doesn't work

### ISSUE THREAD

**Issue by suzuhiroruri** [stashapp/CommunityScrapers#1187]
[JavLand.yml](https://github.com/stashapp/CommunityScrapers/blob/master/scrapers/JavLand.yml) doesn't work

**Comment by bnkai** [comment]
Seems to work fine for me (both scene/movie scrapers)
Can you paste a `url` you tried and it didnt work?

Also for future reference please post broken scrapers reports in the relevant issue #123

**Comment by suzuhiroruri** [comment]
Really??
I coudn't find the scraper at scene scrapers.

**Comment by suzuhiroruri** [comment]
Really??
I couldn't find the scraper at scene scrapers.

**Comment by suzuhiroruri** [comment]
Sorry.
It worked.
