### ISSUE TITLE
CopyFromScene: could not unmarshal json from script output: EOF

### ISSUE THREAD

**Issue by aloysiu3** [stashapp/CommunityScrapers#1234]
CopyFromScene gallery scraper not working

**Comment by DogmaDragon** [comment]
What does the log say? `Settings > Logs`

**Comment by aloysiu3** [comment]
Info
2023-01-05 11:46:58
Error   
could not unmarshal json from script output: EOF
2023-01-05 11:46:58
Error   
[Scrape / Copy from Scene] }
2023-01-05 11:46:58
Error   
[Scrape / Copy from Scene] }
2023-01-05 11:46:58
Error   
[Scrape / Copy from Scene] }
2023-01-05 11:46:58
Error   
[Scrape / Copy from Scene]   name
2023-01-05 11:46:58
Error   
[Scrape / Copy from Scene] id
2023-01-05 11:46:58
Error   
[Scrape / Copy from Scene] tags{
2023-01-05 11:46:58
Error   
[Scrape / Copy from Scene] }
2023-01-05 11:46:58
Error   
[Scrape / Copy from Scene]   name
2023-01-05 11:46:58
Error   
[Scrape / Copy from Scene] id
2023-01-05 11:46:58
Error   
[Scrape / Copy from Scene] performers{
2023-01-05 11:46:58
Error   
[Scrape / Copy from Scene] }
2023-01-05 11:46:58
Error   
[Scrape / Copy from Scene]   name
2023-01-05 11:46:58
Error   
[Scrape / Copy from Scene]   id
2023-01-05 11:46:58
Error   
[Scrape / Copy from Scene] studio{
2023-01-05 11:46:58
Error   
[Scrape / Copy from Scene] organized
2023-01-05 11:46:58
Error   
[Scrape / Copy from Scene] details
2023-01-05 11:46:58
Error   
[Scrape / Copy from Scene] rating
2023-01-05 11:46:58
Error   
[Scrape / Copy from Scene] date
2023-01-05 11:46:58
Error   
[Scrape / Copy from Scene] url
2023-01-05 11:46:58
Error   
[Scrape / Copy from Scene] title
2023-01-05 11:46:58
Error   
[Scrape / Copy from Scene] scenes{
2023-01-05 11:46:58
Error   
[Scrape / Copy from Scene] path
2023-01-05 11:46:58
Error   
[Scrape / Copy from Scene] id
2023-01-05 11:46:58
Error   
[Scrape / Copy from Scene] findGallery(id: $gallery_id){
2023-01-05 11:46:58
Error   
[Scrape / Copy from Scene] Exception: GraphQL query failed:401 - b''. Query: query findGallery($gallery_id: ID!){
2023-01-05 11:46:58
Error   
[Scrape / Copy from Scene]     raise Exception(
2023-01-05 11:46:58
Error   
[Scrape / Copy from Scene]   File "/scrapers/CopyFromScene.py", line 39, in __callGraphQL
2023-01-05 11:46:58
Error   
[Scrape / Copy from Scene] }. Variables: {'gallery_id': '1183'}
2023-01-05 11:46:58
Error   
[Scrape / Copy from Scene]     result = __callGraphQL(query, variables)
2023-01-05 11:46:58
Error   
[Scrape / Copy from Scene]     result = findGallery(fragment['id'])
2023-01-05 11:46:58
Error   
[Scrape / Copy from Scene]   File "/scrapers/CopyFromScene.py", line 71, in findGallery
2023-01-05 11:46:58
Error   
[Scrape / Copy from Scene] Traceback (most recent call last):
2023-01-05 11:46:58
Error   
[Scrape / Copy from Scene]   File "/scrapers/CopyFromScene.py", line 80, in <module>
2023-01-05 11:46:58
Error   
[Scrape / Copy from Scene] input: {"clientMutationId": null, "id": "1183", "title": "103775", "url": "", "date": null, "details": "", "rating": null, "rating100": null, "organized": null, "scene_ids": null, "studio_id": null, "tag_ids": null, "performer_ids": null, "primary_file_id": null}

**Comment by bnkai** [comment]
<Exception: GraphQL query failed:401>
It seems like an auth error? The scraper  needs `py_common/config.py`to be configured correctly with the `url` to access stash and  stash's `api_key`. (if you dont have an api key you will need to generate one)
