### ISSUE TITLE
Studio scraping in Mindgeek.yml is broken as well as RealityKings support

### ISSUE THREAD

**Issue by aussiehuddo** [stashapp/CommunityScrapers#1262]
I have found on mofos.com that when scraping scenes the correct Studio is not scraped.

eg. https://www.mofos.com/scene/8455561/roommates-lotion-motion Should have Pervs on Patrol as the studio, instead it is just listed as Mofos.

Reality Kings support is broken:

eg. https://www.realitykings.com/scene/8461761/let-me-show-you-two scrapes correctly with correct studio

https://www.rk.com/scene/8461761/let-me-show-you-two does not scrape all information (only incorrect studio as above, tags, image)

**Comment by bnkai** [comment]
MindGeek related scraping should eventually be moved to the MindGeekAPI python scraper to avoid all the issues you mention and reduce maintenance overhead. 
Although still a draft <https://github.com/stashapp/CommunityScrapers/pull/1240> should work ok for now

**Comment by Maista6969** [comment]
Superseded by #1641
