### ISSUE TITLE
Brazzers is broken

### ISSUE THREAD

**Issue by Karlsson74** [stashapp/CommunityScrapers#1290]
For some time now I have been having problems using the Brazzers scraper. 

Neither **PerformerByURL** nor **PerformerByName** work. 

When trying to use **sceneByURL** I get the error 

"**_could not retrieve attribute "outerHTML": exception "Uncaught" (2:4): TypeError: $x is not a function at <anonymous>:3:5_**"

I have set up Pyton, CDP and a Scraper User Agent.

Do you guys have a suggested solution?

**Comment by aussiehuddo** [comment]
update #1240 is the solution

**Comment by Maista6969** [comment]
Solved by the API scraper in in #1641
