### ISSUE TITLE
AnimeCharactersDatabase is broken

### ISSUE THREAD

**Issue by bennyz327** [stashapp/CommunityScrapers#1295]
Doesn't show anything either by name or by url

**Comment by DogmaDragon** [comment]
There is <https://github.com/stashapp/CommunityScrapers/issues/123> for reporting broken scrapers.

**Comment by feederbox826** [comment]
Unable to repro, can you send specific links that don't work? It sounds like you are just blocked from the site without VPN

**Comment by bennyz327** [comment]
so, I need to use VPN if I want using this scraper?
but why?
I can access animecharactersdatabase.com correctly using my browser.

**Comment by feederbox826** [comment]
It works fine for me, send specific links that don't work, otherwise it sounds like the site is blocking you

**Comment by feederbox826** [comment]
Cannot repro, please reopen with broken URLs and test with VPN
