### ISSUE TITLE
Scraper "21Roles" not visible

### ISSUE THREAD

**Issue by Roycinger** [stashapp/CommunityScrapers#1319]
Hi Community,

I set up the scraper and the Chrome CDP path in my scraping settings.
However, the mentioned scraper is not visible in the edit dialogue of a scene.

Is there more to do than setting up the Chrome CDP path?

Thanks

**Comment by DogmaDragon** [comment]
You can try pending Python scraper https://github.com/stashapp/CommunityScrapers/pull/1288
