### ISSUE TITLE
Created new scraper, how do I upload for review

### ISSUE THREAD

**Issue by iamcademan** [stashapp/CommunityScrapers#1335]
Created a scraper but, I am not sure how to upload.  Not really familiar with Github :-)

**Comment by DogmaDragon** [comment]
1. Read https://github.com/stashapp/CommunityScrapers#contributing
2. Open https://github.com/stashapp/CommunityScrapers 
3. Click Fork ![image](https://github.com/stashapp/CommunityScrapers/assets/103123951/338c9252-5432-4b00-97d2-a14e4aeb81a4)
4. Go to your forked repository
5. Upload your scraper
6. Update `SCRAPERS-LIST.md` with your scraper information
7. Go back to your forked repository and it will show you a button at the top that offers to submit a pull request.
8. Click `Pull Request` and fill in the details. 

It might look complicated, but it's just a lot of navigating. 

If you have any issues or questions ping me `@DogmaDragon`.
