### ISSUE TITLE
Request with possible Bounty [ .party site to Stash] [json file to stash]

### ISSUE THREAD

**Issue by Tr1n1ty1** [stashapp/CommunityScrapers#1418]
Hey,
I am looking for a scraper that can use a file created by 
https://github.com/darkdragn/party
to scrape all the metadata to stash

the party site is a community site to mass scrape OF/Fansly - the metadata does exist (tied to the filename) but needs to get parsed into Stash

I am willing to put up a bounty depending on the difficulty of the endeavor, maybe an external script is required to batch update the info into stash, not sure about that since I'm not a coder 

The output file is a json file with decent formatting

**Comment by scruffynerf** [comment]
Already exists.  We have a scraper to do this.  Not sure it'll make it into official repo, but TBD.  Visit Stash Discord, and come to #FansDB channel.  or see https://github.com/feederbox826/FansDB-SHALookup

**Comment by A-Random-Mf** [comment]
> Hey, I am looking for a scraper that can use a file created by https://github.com/darkdragn/party to scrape all the metadata to stash
> 
> the party site is a community site to mass scrape OF/Fansly - the metadata does exist (tied to the filename) but needs to get parsed into Stash
> 
> I am willing to put up a bounty depending on the difficulty of the endeavor, maybe an external script is required to batch update the info into stash, not sure about that since I'm not a coder
> 
> The output file is a json file with decent formatting

This is also EXACTLY what I wanna do. I have local metadata to feed to stash. I dont wanna scrape su/of directly as that would be much slower

**Comment by Hydronicx** [comment]
I have a personal Python script that does this by editing the database file directly. Would you be interested?
