### ISSUE TITLE
Add Fisting Inferno to Scraper list/download

### ISSUE THREAD

**Issue by Lamda604** [stashapp/CommunityScrapers#1468]
Fisting Inferno is also an Algolia based site. I just copied an existing yml and changed the values. Seems to work ok.

[Algolia_FistingInferno.yml.txt](https://github.com/stashapp/CommunityScrapers/files/12709692/Algolia_FistingInferno.yml.txt)

**Comment by Maista6969** [comment]
Needed to adjust Algolia a little bit to return the correct studio name: added in c5faefe

Thank you for your contribution 🙂
