### ISSUE TITLE
BlurredMedia.yml was not pulling Title or description, I've made updates

### ISSUE THREAD

**Issue by Lamda604** [stashapp/CommunityScrapers#1495]
Title was coming in as "Notifications" and no description was coming through. I've updated it to now pull the proper title and description.
[BlurredMedia.yml.txt](https://github.com/stashapp/CommunityScrapers/files/12853707/BlurredMedia.yml.txt)

**Comment by Maista6969** [comment]
Thank you for contributing! The normal route is to open up a [pull request]() but I'll just add this to the repo for you this time, feel free to reach out if you're looking to contribute more and I can guide you through the PR creation process 🙂

**Comment by Lamda604** [comment]
Thank you @Maista6969. I've actually only ever contributed 3 times on Github and the first time wasn't even with any coding lol so I'm sorry I didn't follow a normal process. I don't even do coding regularly - I just opened the scraper file and worked it out/backwards engineered it :P If I get more involved in the future, I'll look into opening a pull request and what that entails. Thanks again!
