### ISSUE TITLE
Feature: Adding contribution section to Readme.md file.

### ISSUE THREAD

**Issue by Kalyanimhala** [stashapp/CommunityScrapers#1499]
There is no Contributors section in readme file .
As we know Contributions are what make the open-source community such an amazing place to learn, inspire, and create.
Any contributions make are greatly appreciated, for that we need to add new section for contributors and adding to the readme file!

![contributors](https://github.com/stashapp/CommunityScrapers/assets/147402107/79828631-1a23-4b93-89db-def3cafe2c1b)

**Comment by Kalyanimhala** [comment]
@evandeaubl kindly assign me this #1499  issue I want to work on it.

**Comment by evandeaubl** [comment]
I assume I was mistagged. I don’t have the ability to reassign issues on this project. Just a contributor. 🙂

**Comment by Maista6969** [comment]
Github already [shows this](https://i.imgur.com/tYopZ5y.png) so I don't see how adding it to the readme would add anything to the project beyond an additional maintenance burden
