### ISSUE TITLE
[The Score Group] Pull correct studio from Pornmegaload links

### ISSUE THREAD

**Issue by Ronnie711** [stashapp/CommunityScrapers#1588]
Currently Scenes scraped using pornmegaload.com will use that as the studio link. All (99.99%) scenes are available from one of the Score subsites & then also distributed on PML, so aren't technically a PML release.

I looked through page source in the hope that there was a field for the correct studio but alas we're not that lucky!

However, after a bit of detective work the URL's for 'Download Trailer' appear to be consistent & mention the correct studio in the url string

Example A:

URL: https://www.pornmegaload.com/hd-porn-scenes/Jojo-Austin/75088/

Download trailer: &nbsp; <a href="//cdn77.scoreuniverse.com/18eighteen/scenes/JojoAustin_39826/Trailers/pornmegaload/mp4/JojoAustin_39826_360p.mp4"

Example B:

URL: https://www.pornmegaload.com/hd-porn-scenes/Diamond-Mason/44087/

Download trailer: &nbsp; <a href="[//cdn77.scoreuniverse.com/bootyliciousmag/videos/ASStonishingVideos/DiamondMason_26449/Trailers/pornmegaload/DiamondMason_26449_640x360_800_T01.mp4"

**Comment by Maista6969** [comment]
Thanks for this tip! I was able to rewrite the studio pattern for The Score Group and it should now return the correct studio for any scene, no matter which domain it is scraped from! I based my work on the list of [substudios on StashDB](https://stashdb.org/studios/1a3a18b5-8bb5-463c-8306-537aa812f604) so if I missed any please let me know 👍 

I also added domain patterns for every valid Score domain I could find, even the smaller ones. Some of these use _slightly_ different layouts and so will only return partial results, and others are only serving up rebranded versions of scenes. For example the scenes I tested from flatandfuckedmilfs.com are mostly 50 Plus MILFs scenes and these will of course be returned as 50 Plus MILFs scenes. Users who want to use the brand will have to change these manually 😅
