### ISSUE TITLE
Update AdultPrime Scraper 

### ISSUE THREAD

**Issue by thedesi1** [stashapp/CommunityScrapers#1681]
@Maista6969 is it possible use regex replace for [AdultPrime Scraper](https://github.com/stashapp/CommunityScrapers/blob/master/scrapers/AdultPrime.yml) and replace this
https://adultprime.com/signup?galleryId=132917 with this https://adultprime.com/studios/video/132917

**Comment by Maista6969** [comment]
Maybe I'm not understanding your request correct, but the [scraper already replaces the returned URL](https://github.com/stashapp/CommunityScrapers/blob/87d1ae6c252b7cc557868c4e7977ffce3107213b/scrapers/AdultPrime.yml#L29-L34) with the pattern you're requesting

If you mean that the scraper should work when you give it the first URL, that's not really possible for regular Stash scrapers at this point: we'd have to rewrite the scraper to be a script scraper, which is absolutely possible but makes it harder both to maintain and for people to use

**Comment by thedesi1** [comment]
Ah I see, you mean if I scrape it would but URL scrapper its not possible.

**Comment by Maista6969** [comment]
Correct: URL scrapers have no way to access the URL it is being run on and cannot change it before it is fetched, this would require changes in Stash 🙂
