### ISSUE TITLE
[SCRAPER REQUEST] JSON file created by yt-dlp

### ISSUE THREAD

**Issue by ClearBlueOcean** [stashapp/CommunityScrapers#1685]
It would be very helpful if someone created a scraper that used the .info.json file created by [yt-dlp](https://github.com/yt-dlp/yt-dlp).

[yt-dlp](https://github.com/yt-dlp/yt-dlp) is a maintained fork of abandoned project [youtube-dl](https://github.com/ytdl-org/youtube-dl). It supports downloads from the [most popular porn sites](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md), including pornhub, xhamster, xnxx, xvideos, and many more. If you pass the `--write-info-json` option when downloading, it will scrape the download site and save all of the metadata in a JSON file (so there's no need for a Stash scraper to search for the URL and re-scrape the website).

Creating a scraper is beyond when I can do right now, but I hope someone will take up the project.

Example:
`yt-dlp --write-info-json https://www.pornhub.com/view_video.php?viewkey=65ca80a5653f0`

From that command, you get two files (naming convention set via config):
  `The pool cleaner cleaned my pipes, my mouth was full of joy-pornhub.com-65ca80a5653f0.mp4`
and
  `The pool cleaner cleaned my pipes, my mouth was full of joy-pornhub.com-65ca80a5653f0.info.json`
 
The .info.json file is large. Here's some of the relevant info, with TRUNCATED noting where I've stripped out some of the longer bits.

```
{
  "id": "65ca80a5653f0",
  "uploader": "Solazola",
  "uploader_id": "solazola",
  "upload_date": "20240212",
  "title": "The pool cleaner cleaned my pipes, my mouth was full of joy",
  "thumbnail": "https://ei.phncdn.com/videos/202402/12/448057751/thumbs_45/(m=eaAaGwObaaaa)(mh=MCWiyFhxay9C8VJE)9.jpg",
  "duration": 1530,
  "like_count": 9725,
  "dislike_count": 850,
  "comment_count": 124,
  "formats": [
    {
      "TRUNCATED": "FORMATS ARRAY CONTAINS APPROX 280 LINES"
    }
  ],
  "age_limit": 18,
  "tags": [
    "blowjob cum in mouth",
    "blowjob",
    "TRUNCATED"
  ],
  "categories": [
    "Babe",
    "Blowjob",
    "TRUNCATED"
  ],
  "cast": [
    "Linda Lovelace"
  ],
  "subtitles": {},
  "thumbnails": [
    {
      "url": "https://ei.phncdn.com/videos/202402/12/448057751/thumbs_45/(m=eaAaGwObaaaa)(mh=MCWiyFhxay9C8VJE)9.jpg",
      "id": "0"
    }
  ],
  "timestamp": 1707770647,
  "view_count": 3864037,
  "webpage_url": "https://www.pornhub.com/view_video.php?viewkey=65ca80a5653f0",
  "webpage_url_basename": "view_video.php",
  "webpage_url_domain": "pornhub.com",
  "extractor": "PornHub",
  "extractor_key": "PornHub",
  "display_id": "65ca80a5653f0",
  "fulltitle": "The pool cleaner cleaned my pipes, my mouth was full of joy",
  "duration_string": "25:30",
  "epoch": 1710129291,
  "format_id": "hls-1824-1",
  "url": "TRUNCATED",
  "manifest_url": "TRUNCATED",
  "tbr": 1824.327,
  "ext": "mp4",
  "fps": 24,
  "protocol": "m3u8_native",
  "has_drm": false,
  "width": 1920,
  "height": 1080,
  "vcodec": "avc1.640032",
  "acodec": "mp4a.40.2",
  "dynamic_range": "SDR",
  "resolution": "1920x1080",
  "aspect_ratio": 1.78,
  "http_headers": {
    "TRUNCATED": "TRUNCATED"
  },
  "video_ext": "mp4",
  "audio_ext": "none",
  "format": "hls-1824-1 - 1920x1080",
  "_type": "video"
}
```

**Comment by MortonBridges** [comment]
[YT-dlp.zip](https://github.com/stashapp/CommunityScrapers/files/14985694/YT-dlp.zip)
Give this a try.  Unzip into scrapers/community.

If this looks good I'll check it in.  I'm using the JSON pasted in the issue for testing, but have not run yt-dlp to test with other files.

**Comment by ClearBlueOcean** [comment]
Thanks for giving this one a go. It would be great to get a scraper for yt-dlp (and projects that use it, like [metube](https://github.com/alexta69/metube)).

I'm getting this when I try to run the scraper:
```ERRO[2024-04-16 20:19:57] [Scrape / YT-dlp] [GraphQL] HTTP Error 401, Unauthorised. You can add a API Key in 'config.ini' in the 'py_common' folder 
ERRO[2024-04-16 20:19:57] [Scrape / YT-dlp] Traceback (most recent call last): 
ERRO[2024-04-16 20:19:57] [Scrape / YT-dlp]   File "/home/john/.stash/scrapers/YT-dlp/YT-dlp.py", line 96, in <module> 
ERRO[2024-04-16 20:19:57] [Scrape / YT-dlp]     ret = scene_from_json(js) 
ERRO[2024-04-16 20:19:57] [Scrape / YT-dlp]           ^^^^^^^^^^^^^^^^^^^ 
ERRO[2024-04-16 20:19:57] [Scrape / YT-dlp]   File "/home/john/.stash/scrapers/YT-dlp/YT-dlp.py", line 44, in scene_from_json 
ERRO[2024-04-16 20:19:57] [Scrape / YT-dlp]     assert response is not None 
ERRO[2024-04-16 20:19:57] [Scrape / YT-dlp]            ^^^^^^^^^^^^^^^^^^^^ 
ERRO[2024-04-16 20:19:57] [Scrape / YT-dlp] AssertionError             
ERRO[2024-04-16 20:19:57] could not unmarshal json from script output: EOF 
ERRO[2024-04-16 20:19:57] scrapeSingleScene: input: scrapeSingleScene scraper YT-dlp: could not unmarshal json from script output: EOF ```

Some full .json files are attached if they're helpful.
[Full outputs yt-dlp json.zip](https://github.com/stashapp/CommunityScrapers/files/15004396/Full.outputs.yt-dlp.json.zip)

**Comment by MortonBridges** [comment]
Here's another attempt.  I needed to check if elements in the JSON existed before blindly loading them in the scene information.
[YT-dlp.zip](https://github.com/stashapp/CommunityScrapers/files/15006349/YT-dlp.zip)

**Comment by MortonBridges** [comment]
Implemented in [PR 1779](https://github.com/stashapp/CommunityScrapers/pull/1779)
