### ISSUE TITLE
Scraping links from EA returns the Movie title instead of the Studio title.

### ISSUE THREAD

**Issue by Qlupic** [stashapp/CommunityScrapers#1701]
Scraping links from EA on scenes returns the Movie title instead of the Studio title. I am using version `97bec71` (11/22/2023 12:53:44 AM). Seems like `serie_name`is being used which is not the right key to use.

![1553432444865823](https://github.com/stashapp/CommunityScripts/assets/73070379/cb5f66e1-c2ac-4ef9-9a0e-5b647e3018e7)

**Comment by MortonBridges** [comment]
Fix implemented in [PR 1776](https://github.com/stashapp/CommunityScrapers/pull/1776).
