### ISSUE TITLE
Blacked.com not working

### ISSUE THREAD

**Issue by thecat18** [stashapp/CommunityScrapers#171]
Is the scraper not working or do i have rename the scene a certain way?

**Comment by bnkai** [comment]
Just tried and it works ( sample URL `https://www.blacked.com/summer-dj-fling` ).
Have you setup CDP properly though ( settings -> configuration ) ? The specific scraper needs that.

**Comment by thecat18** [comment]
Thanks but I'm not sure what I put in the settings the address of the scene is https://www.blacked.com/perfect-blonde-with-2-monster-black-cocks
Also how do I know which scrapers needs cdp. a little over my head.

**Comment by Belleyy** [comment]
> Thanks but I'm not sure what I put in the settings 

You put the path to your chrome.exe (Google chrome executable) like `C:\Users\Winter\AppData\Local\Chromium\Application\chrome.exe`

> Also how do I know which scrapers needs cdp. a little over my head. 

In the scraper file, these line enable the CDP 
```
driver:
  useCDP: true
```

> Also when adding a full movie is adultdvdempire.com is also a cdp? it wasn't working for me.

adultdvdempire scraper don't use CDP. Maybe you got a problem because it's a **Movie** scraper not a **Scene** scraper.

**Comment by thecat18** [comment]
Well guess I am out of luck I use Firefox. Also adultdvdempire I was trying to use in the movie section because iafd didn't have enough info & no pics. If I want to use this better I guess I need chrome.

**Comment by Belleyy** [comment]
I also use mainly use Firefox, but i have other browser.
For the User-Agent i use `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0`
Check the Logs - Debug to see what the scraper get. And you can write in the scraper (AdultEmpire.yml) these lines to get the exact HTML, it scrape
```
debug:
  printHTML: true
```

**Comment by bnkai** [comment]
@thecat18 as stated above `blacked.com` scrapers requires CDP and thus the use ( and configuration ) of a chromium based browser, the user agent isn't enough.

> how i exit stash & get back in & don't have to put my info in again of where my files are located?
what do you mean? did you hit the `save` button after you  completed the configuration changes ?

**Comment by thecat18** [comment]
> 
> 
> @thecat18 as stated above `blacked.com` scrapers requires CDP and thus the use ( and configuration ) of a chromium based browser, the user agent isn't enough.
> 
> > how i exit stash & get back in & don't have to put my info in again of where my files are located?
> 
> what do you mean? did you hit the `save` button after you completed the configuration changes ?

Ok I was using the link in bookmarks that opened it on that page. Also can I use microsoft edge to make blacked.com work?

**Comment by thecat18** [comment]
> printHTML: true

debug says this for trying to add the blacked.com scene, but 1st I get the chrome error then this & after is the debug when I try to use adultdvdempire when adding a movie.  I don't understand what this stuff means.
20-09-16 19:35:21Debug   SQL: SELECT DISTINCT scenes.id FROM scenes 
		left join scene_markers on scene_markers.scene_id = scenes.id
		left join performers_scenes as performers_join on performers_join.scene_id = scenes.id
		left join movies_scenes as movies_join on movies_join.scene_id = scenes.id
		left join studios as studio on studio.id = scenes.studio_id
		left join galleries as gallery on gallery.scene_id = scenes.id
		left join scenes_tags as tags_join on tags_join.scene_id = scenes.id
	 GROUP BY scenes.id  ORDER BY scenes.date ASC, bitrate DESC, framerate DESC, scenes.rating DESC, scenes.duration DESC LIMIT 40 OFFSET 0 , args: []

SQL: SELECT DISTINCT movies.id FROM movies 
	left join movies_scenes as scenes_join on scenes_join.movie_id = movies.id
	left join scenes on scenes_join.scene_id = scenes.id
	left join studios as studio on studio.id = movies.studio_id
 GROUP BY movies.id  ORDER BY movies.name COLLATE NOCASE ASC LIMIT 40 OFFSET 0 , args: []

**Comment by thecat18** [comment]
> 
> 
> I also use mainly use Firefox, but i have other browser.
> For the User-Agent i use `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0`
> Check the Logs - Debug to see what the scraper get. And you can write in the scraper (AdultEmpire.yml) these lines to get the exact HTML, it scrape
> 
> ```
> debug:
>   printHTML: true
> ```

Also it looks I got the user agent right but what is able to do since it seems like only chrome will work with blacked.com & probably others too/.

**Comment by bnkai** [comment]
Closing as the scraper is working.
