### ISSUE TITLE
Bromo Wrong Url for newer scenes / AyloAPI

### ISSUE THREAD

**Issue by gimmeliina** [stashapp/CommunityScrapers#1811]
** Scraper name **
Bromo

** Scraper method **
**Scene** / Gallery / Movie / Performer?
Newer scenes are moved to men.com and are not in bromo.com anymore.
Scraper overrides men.com url with incorrect bromo.com url.

Older scenes can be in both, but some are only in Bromo.com

**Comment by Maista6969** [comment]
Thanks for reporting this, I tested with a bunch of scenes from their videos page and found that they all come back from the API with correct studio information now. When I tested them [back in January](https://github.com/Maista6969/AyloAPI-beta/blob/master/overview.md#bromo) they had some mixed-up studio names but that seems to have been corrected now, so I removed the override in [Bromo.py](https://github.com/stashapp/CommunityScrapers/blob/master/scrapers/Bromo/Bromo.py#L20-L21) in version `95056a4`
