### ISSUE TITLE
Scraper Request For Ersties.com

### ISSUE THREAD

**Issue by shark-lasers58** [stashapp/CommunityScrapers#1819]
### Example URLs

Performer: https://ersties.com/profile/447
Scene: https://ersties.com/profile/3046

### Notes

A free account is needed to view scene and performer information.

**Comment by pops64** [comment]
Yeah I looked at this. Being behind a paywall/account locked makes this site difficult to scrape.

**Comment by Maista6969** [comment]
Even worse: scenes do not have pages of their own and only show up on performer profiles. If we use the [performer URL](https://ersties.com/profile/447) as a scene URL, which of the three scene results should we return?

And creating a performer scraper wouldn't save a lot of effort either:  these pages only contain a name, an image and a short blurb

It's free to make an account (we could just include the credentials in the scraper) and their API is _not very well designed_ so if someone who cares for this kind of content has the skills it would be possible to build a scraper for sorts for this

**Comment by pops64** [comment]
Like you said. I look at again after my comment. It may not be possible at all due their file name convention on downloads. The only way would be like Abby Winters where you find the scene and provide the link. But then your going through stash's built in scraper which can't handle a paywall/API call. Unless I making an assumption(Hidden context there :P)

**Comment by shark-lasers58** [comment]
> Even worse: scenes do not have pages of their own and only show up on performer profiles. If we use the [performer URL](https://ersties.com/profile/447) as a scene URL, which of the three scene results should we return?

I figured out this part. The comments icon under a scene links to a scene specific page which has Titles, models, and tags listed.

Ex. https://ersties.com/videos?query=melli#play-7976-comments

![image](https://github.com/user-attachments/assets/c4097705-24fa-48a7-8e08-9886c07ff156)

**Comment by shark-lasers58** [comment]
I put together some sample python code to get the scene data:
https://gist.github.com/shark-lasers58/bc788e90e3a95fd7e1286c1b7dd16493

The output looks like this:
https://gist.github.com/shark-lasers58/44caa43ae32f9226b357fa0b952813ad

Not sure if this is helpful to anyone who is more familiar with creating scrapers but I can start to look into how to build out a scraper using this information.

**Comment by shark-lasers58** [comment]
Thank you for this information. I will definitely start to review this and try to implement your suggestions. 

I started a fork to work on this and and be found here:
https://github.com/shark-lasers58/CommunityScrapers/blob/master/scrapers/Ersties/Ersties.py

I think I have the bulk of the scraping figured out but need to test it. And obviously try to implement your suggestions. Any additional feedback is appreciated.

**Comment by shark-lasers58** [comment]
> Your using the API call. You would still need to figure out which scene or scene id to scrape. Which isn't included in the download file name. Yes it appears the scene ids may be on the scene page. But ersties breaks the link by haveing obscure file names. You could with a lot of work.
> 
> Pseudo code. Take in the file name -> Query to `https://api.ersties.com/videos?page=1&id=&term=<search_query_in_url_encode>&search_type=query` based on the first part of the file name ->Match the file name using videos.title_en(Possibly de or fr) for all the details
> 
> A few notes. The conversion from the file name must be the OG assigned file name, You may struggle with matching and Query if the file names don't hold true for all videos. You may struggle with determining what is the actor portion and what is the junk portion for the query. Aka `https://api.ersties.com/videos?page=1&id=&term=Stacie+%26+Izzy+in+Action+2&search_type=query` returns no results but `https://api.ersties.com/videos?page=1&id=&term=Stacie+%26+Izzy&search_type=query` returns correct results with using `Stacie & Izzy in Action 2 HQ.mp4` as an OG file name.
> 
> Also of note. In you code you ask for a prompt for user input and password. This is bad coding. Have the user edit the python file to store there current `access_token` cookie. Here is the curl command with the header info based on your code
> 
> ```
> curl 'https://api.ersties.com/videos?page=1&id=&term=Stacie+%26+Izzy&search_type=query' \
>   -H 'authorization: Bearer <users_access_token_cookie>' \
>   -H 'cookie: access_token=<users_access_token_cookie>' \
>   -H 'x-visit-uid: <uid>'
> ```
> 
> Another note using `Dina Action HQ.mp4` as an OG filename returns a title of `Action`
> 
> Look at any of the API python scrapers for stash on how to take in data and look at Ifeelmyself at how an auth cookie is implemented. The biggest hurdle will be all the possible combinations for titles.
> 
> This is just a starting point. There are lots of other combinations of user input that need to be handled. Also determine what the maintainers of stash want as the data. Look to stashDB with the common theme of what is grabbed from ersties. If this sounds like it will be a struggle, I can help

Rereading your post, I think the scope of what my python skills will be able to accomplish is to set up a simple URL scraper using the video links like this:
`https://ersties.com/profile/3265#play-8187-comments`

Using these links I can pull in the video code, `8187` in this example, and build the api call to get that data. 

I tried to run this against a scene in Stash but received this error:
`ERRO[2024-10-20 20:36:00] could not unmarshal json from script output: invalid character 'V' looking for beginning of value 
ERRO[2024-10-20 20:36:00] scrapeSceneURL: input: scrapeSceneURL could not unmarshal json from script output: invalid character 'V' looking for beginning of value `

I'm not sure what to do. I suspect I'm either not reading the input from Stash or not sending back the correct output, but I don't know how to troubleshoot this. Any guidance would be appreciated.

Also I was able to use your recommendation to implement auth using Bearer Token/cookie/UID in the header. Thanks!

**Comment by shark-lasers58** [comment]
> I tried to run this against a scene in Stash but received this error:
> `ERRO[2024-10-20 20:36:00] could not unmarshal json from script output: invalid character 'V' looking for beginning of value ERRO[2024-10-20 20:36:00] scrapeSceneURL: input: scrapeSceneURL could not unmarshal json from script output: invalid character 'V' looking for beginning of value `

I realized what this issue was. I had a `print()` for troubleshooting still in the code. I've gotten past that but I'm still getting errors for `'studio'`, `'tags'`, and `'performers'`. Example errors below:
`ERRO[2024-10-20 21:00:59] [Scrape / Ersties] {"url": "https://ersties.com/profile/2018#play-4250-comments"} 
ERRO[2024-10-20 21:04:00] could not unmarshal json from script output: json: cannot unmarshal string into Go struct field ScrapedScene.studio of type models.ScrapedStudio 
ERRO[2024-10-20 21:04:00] scrapeSceneURL: input: scrapeSceneURL could not unmarshal json from script output: json: cannot unmarshal string into Go struct field ScrapedScene.studio of type models.ScrapedStudio `

`ERRO[2024-10-20 21:04:00] [Scrape / Ersties] {"url": "https://ersties.com/profile/2018#play-4250-comments"} 
ERRO[2024-10-20 21:05:06] could not unmarshal json from script output: json: cannot unmarshal string into Go struct field ScrapedScene.tags of type models.ScrapedTag 
ERRO[2024-10-20 21:05:06] scrapeSceneURL: input: scrapeSceneURL could not unmarshal json from script output: json: cannot unmarshal string into Go struct field ScrapedScene.tags of type models.ScrapedTag `

`ERRO[2024-10-20 21:04:00] [Scrape / Ersties] {"url": "https://ersties.com/profile/2018#play-4250-comments"} 
ERRO[2024-10-20 21:05:06] could not unmarshal json from script output: json: cannot unmarshal string into Go struct field ScrapedScene.tags of type models.ScrapedTag 
ERRO[2024-10-20 21:05:06] scrapeSceneURL: input: scrapeSceneURL could not unmarshal json from script output: json: cannot unmarshal string into Go struct field ScrapedScene.tags of type models.ScrapedTag `

**Comment by pops64** [comment]
It could use some improvements. Your looking for a very specific link. It should be more generalized/handle different inputs. The hardest thing we should ask a user to do is input the auth cookie. The UID being generated randomly is fine. 

At a minimum stash should be able to take in the scene url `https://ersties.com/profile/2758` for example and find the matching scene. Obviously, with Ersties we would need more data than just a url(The scene title or file name). But the URL should be easy to find for the user not something they have to dig through the html for and should be optional due to the multiple scenes per link and other data better suited for searching. 

And since we are using python we should also be able to handle using the tagger function. Which takes the file name input. Which is enough data to trace to a correct scene meta data.

The only annoying thing that is missing is the date of release which is required for stashDB. This could be done but only the update part of the query string returns dates from the API. 

I always cheat and use code already submitted for the code base has templates. It also keeps the code format the same or standardized for the project. I know MetArt scraper is an API call. And Ifeelmyself handles auth cookies. Look to theses for templates and error printing

**Comment by shark-lasers58** [comment]
> But the URL should be easy to find for the user not something they have to dig through the html for

The URL used isn't something that needs to be pulled from the HTML. Its easily found from the Comments button under each video. 

I'd argue that the scene URL you used as an example, `https://ersties.com/profile/2758`, is actually a Group/Movie and the scene URL is actually `https://ersties.com/profile/2758#play-7931-comments` for the "Playdate" scene. This makes more sense for Specials like `https://ersties.com/profile/2702` were each video in this "profile" is for this specific Group/Movie. 

It gets a little less cut and dry for the Single Performer pages as those can have multiple "Groups" of videos. The initial example you used for Dina, `https://ersties.com/profile/2758`, appears to have three Groups of scenes listed, "Spring Has Sprung and So Has Dina", "Sexy Solo Stroll", and "Dina Enjoys Some Lost Leftovers from Her Lover". You can see the HTML does actually break these up:
![image](https://github.com/user-attachments/assets/89beb226-ffb4-40a1-a34b-25adb856951a)

Regardless, the video (scene) URLs are a standard format, `https://ersties.com/profile/xxxx#play-yyyy-comments`.

>And since we are using python we should also be able to handle using the tagger function. Which takes the file name for input. Which is enough data to trace to a correct scene meta data.

I'm not really familiar with this. Is there a link to some reference material I could read about this functionality?

>The only annoying thing that is missing is the date of release which is required for stashDB. This could be done but only the update directory of the query string returns dates from the API.

This is the biggest problem I've run into. They list a "Last Updated" date on the Scene/Group details but that isn't always accurate as I've found the date can be much later that it should be (probably due to an update post release).

For example, 'https://ersties.com/profile/2212', which is the first release in the series has a date of `12/23/2023`, but `https://ersties.com/profile/2314`, which is the second release has a date of `03/18/2022`. We _could_ pull in this date but I think due to it not necessarily being the release date it should be left up to the user to determine the date to apply, which is unfortunate.

**Comment by pops64** [comment]
Yeah I still don't like that your looking for a very obscure link. The tagger function I might have misname it. But it is the function that you can use to scrape stashDB for a matching Phash etc. It can also be used in other ways. 

Check out the Ifeelmyself scraper. This scraper takes in a file name. Uses regex to trim it down to something usable and searches for it on ifeelmyself. Then populates the scene metadata with what it finds. If file names are standard and no duplication than this would be a better/in addition route to search scenes than a URL. 

The video URL may be better or in addition, it can be right clicked copied, but must be clearly stated in a readme file that this what you intend. EG `https://ersties.com/profile/2758#play-7090`  With a clear error printed in the log if an incorrect URL is added, or shown to the user you would have to see if a scraper can do this in stash. 

My thought for the dates was to do a mass query of the update dir. To save on requests you could figure out if the scenes ids count in a standard fashion, Figure out how many per page, do some math to figure out which page the scene ID may be on, check that page for matching, if not branch out in each direction till you find it stopping after X amount to avoid flooding the server with requests, Then grab the date.

**Comment by shark-lasers58** [comment]
> Check out the Ifeelmyself scraper. This scraper takes in a file name. Uses regex to trim it down to something usable and searches for it on ifeelmyself. Then populates the scene metadata with what it finds. If file names are standard and no duplication than this would be a better/in addition route to search scenes than a URL.

I see what you are saying. I think that may need to be a v2 version as I'd need to improve my python skills to try to tackle that.



> The video URL may be better or in addition, it can be right clicked copied, but must be clearly stated in a readme file that this what you intend. EG `https://ersties.com/profile/2758#play-7090` With a clear error printed in the log if an incorrect URL is added, or shown to the user you would have to see if a scraper can do this in stash.

Once I get all of the scraper pieces in place I plan to work on the error outputs.



> Also you should be able to take in a title or scene Id and search the API for a matching scene.

The scene ID would definitely be simple to add as the scraper is already using it, just pulling it from the URL. Title would be more difficult due to the way they title the videos. There are many videos titles `Action 1` and parsing which `Action 1` you are looking for would be challenging.



> he date might just as well have to be left to manual intervention if wanting to add to the scene to stashDB

That is my thought as well.

I've updated the scraper to include Movie/Group scraping from `profile` pages (ex. `https://ersties.com/profile/2390`).

The remaining pieces are to also include a performer scraper using the same `profile` link (they use the `profile` page to list individual performers as well as scene groups) and update error output and documentation. Once that's done I think we should be good to get a v1 submitted as a PR.

**Comment by pops64** [comment]
Yeah that what I was worried about was duplication in download file names and scene names. Which it appears that they do which makes the scrape by fragment tagger function pointless. 

The best would be the two links that include the scene ID like mentioned. Inputted into the URL field. The date would still be hard to get. You just need to make it very clear in the readme where to retrieve scene links and prompt the user if it isn't valid
