### ISSUE TITLE
SexArt returning incorrect director

### ISSUE THREAD

**Issue by FlashSpazzbo** [stashapp/CommunityScrapers#1844]
**Scraper name**

SexArt / SARJ

**Scraper method**
Scene, scraped with URL

**Sample URL**
https://www.sexart.com/model/hayden-hawkens-and-christos-vasilopoulos-and-malena-morgan-and-elle-alexandra-and-kayla-jane-and-daniel-sobieray/movie/20120504/KAMIKAZE_LOVE___CHERRY_PINK_RAGE

## Issue
Scraper incorrectly returning still photographer as additional director.

Using sample URL, scraper should return `Zalman King` in `Director` field, instead is returning `Zalman King, David Golding`

**Comment by MortonBridges** [comment]
Addressed in [PR 1852](https://github.com/stashapp/CommunityScrapers/pull/1852).
