### ISSUE TITLE
[TeamSkeet] Studio Mapping + inconsistent studio scraping from SayUncle

### ISSUE THREAD

**Issue by Ronnie711** [stashapp/CommunityScrapers#1864]
**Mylf/TeamSkeet/SayUncle**

Currently some Sub-studios across the network scrape differently to how they are named on StashDB.

Format of below list is ScrapedName: StashDB Name

**TeamSkeet**
BadMilfs: Bad MILFs
DadCrush: Dad Crush
GingerPatch: Ginger Patch
Not My Grandpa:  Not My Grandpa!
PervMom: Perv Mom
PervTherapy: Perv Therapy
StayHomePov: Stay Home POV
StepSiblings: Step Siblings
TeenJoi: Teen JOI

**MYLF**
AnalMom: Anal Mom
BBCParadise: BBC Paradise
FullOfJoi: Full Of JOI
GotMylf: Got MYLF
LoneMilf: Lone MILF
MilfBody: MILF Body
MomDrips: Mom Drips
MomShoot: Mom Shoot
MylfBlows: MYLF Blows
MylfBoss: MYLF Boss
MylfSelects: MYLF Selects
PervNana: Perv Nana
StayHomeMilf: Stay Home MILF
UsePOV: Use POV

**SayUncle**
Black Godz: BlackGodz
BottomGames: Bottom Games
BoysDoPorn: Boys Do Porn
DadCreep: Dad Creep
DoctorTapes: Doctor Tapes
MilitaryDick: Military Dick
SayUncle AllStars: SayUncle All Stars
StayHomeBro: Stay Home Bro
StickyRub: Sticky Rub
TroopSex: Troop Sex
YesFather: Yes Father

~~SayUncle list could be longer but the scraper isn't consistently pulling a sub-studio. Example: https://www.sayuncle.com/movies/the-deepest-massage Studio should be SayUncle Classics but returns nothing.~~

**Comment by Ronnie711** [comment]
Additional demands 😄 

Enforced tag of ```Re-release``` for re-releases on MYLF/SayUncle/TeamSkeet Classics

Enforced tag of ```Redistribution``` on all MYLF/SayUncle/TeamSkeet X releases

😁

**Comment by MortonBridges** [comment]
@Ronnie711 , can you check if you're on version 5830d0d of the TeamSkeet scraper?  That version is returning "SayUncle Classics" as the studio for me when I scrape the URL you provided.

**Comment by Ronnie711** [comment]
> @Ronnie711 , can you check if you're on version [5830d0d](https://github.com/stashapp/CommunityScrapers/commit/5830d0dbaefb2fb149150ae4a9a3c47f2f032220) of the TeamSkeet scraper? That version is returning "SayUncle Classics" as the studio for me when I scrape the URL you provided.

![image](https://github.com/stashapp/CommunityScrapers/assets/147556958/2cf76b44-ed4a-467f-898b-2f4f7988506a)

![image](https://github.com/stashapp/CommunityScrapers/assets/147556958/ba90ba5d-3a97-4d29-a883-ea250c5cc040)

Can confirm that a) was already on latest version  b) don't have any Say Uncle scenes/studios etc. c) haven't touched the scraper 😄

**Comment by Ronnie711** [comment]
Ignore the last part ... 2 days after installing the scraper ... I just hit reload scrapers ....

![image](https://github.com/stashapp/CommunityScrapers/assets/147556958/9953d08d-33bc-44cf-8a11-0e2dfb9a4f61)

**Comment by Ronnie711** [comment]
SayUncle list updated in original post 👍

**Comment by MortonBridges** [comment]
Mapping the noted studios so that they map what's in StashDB and default "Re-release" tag for "Classics" studios addressed in [PR 1866](https://github.com/stashapp/CommunityScrapers/pull/1866).

I'm cowardly refusing to add "redistribution" to the FOO x BAR studios, since I believe some are legit collabs as opposed to straight redistribution, and also because I'm not sure of the best way to code this so it happens automatically.  But mostly because I'm NOT going to hard-code all the 'x' studios!
