### ISSUE TITLE
pornhub scraper no longer grabbing tags

### ISSUE THREAD

**Issue by Boontato** [stashapp/CommunityScrapers#1912]
used to work, now only grabs title name, date, url, cover image

**Comment by Maista6969** [comment]
Which version of the scraper are you using, and what URL are you trying to scrape? Do you live in a US state that's blocking Pornhub?

I tested this with the current version of the Pornhub scraper, `3c9c93a`, and it's successfully scraping title, date, URL, studio, tags and image

**Comment by Boontato** [comment]
was using the immediate previous version of the scraper and tried the most current version `3c9c93a` 
my files have the ph id as part of the file name and i have also tried using the url to scrape as well. in california so no blocking. running in a docker on my unraid and its able to scrape everything else except tags. also checked docker is up to date as well as restarted the docker just in case.

example urls that i checked does have tags and categories
https://www.pornhub.com/view_video.php?viewkey=66244bf0447bf
https://www.pornhub.com/view_video.php?viewkey=6652eae9e84c7

**Comment by Boontato** [comment]
Testing fresh url and pic of what it scraped
https://www.pornhub.com/view_video.php?viewkey=6663026e41a20
![Screenshot_20240619_105639_Chrome](https://github.com/stashapp/CommunityScrapers/assets/114942870/5e33e2d1-e23d-40a9-8c5e-3c987b1f5c96)

**Comment by Boontato** [comment]
update, i tried removing the user agent string completely and it works, then used google to find my own user agent string to update it and using the updated one it works. consider resolved as it is pulling everything.

**Comment by Maista6969** [comment]
Thank you both for reporting this and for posting the solution you found, I suspect some kind of A/B testing was serving you slightly different HTML from what I was getting 👍
