### ISSUE TITLE
IAFD scraper "processing image: http error 403"

### ISSUE THREAD

**Issue by DDXDB** [stashapp/CommunityScrapers#1923]
When I save the image "processing image: http error 403"
Stash version: v0.26.2
IAFD Scraper version:eb3f2b9

**Comment by DDXDB** [comment]
in logs
`performerUpdate: input: performerUpdate processing image: http error 403`

**Comment by IAmKontrast** [comment]
@DDXDB Do you have more information? Which performer for example.

I couldn't reproduce it with v0.26.2 / IAFD:eb3f2b9

**Comment by feederbox826** [comment]
Can't repro, it sounds like a location issue. Try with a VPN, if it persists, reopen the issue
