### ISSUE TITLE
Pornhub scraper doesn't work

### ISSUE THREAD

**Issue by twist3dimages** [stashapp/CommunityScrapers#1932]
(this is important, be as detailed as you can)

Are you scraping a scene, gallery, movie, or performer? Scene
Scrape with URL? If so, what URLs have you tried?  

Every URL I tried fails now

here's are examples

https://www.pornhub.com/view_video.php?viewkey=647c6491814a4
https://www.pornhub.com/view_video.php?viewkey=ph5ea1d4d610917
Scrape with fragment? If so, what is the filename / title / studio code?  
Scrape with name? Give an example you searched for that caused the scraper to fail

Please check the logs to see if there are any relevant error messages you can include

These are the errors I get. It happens with every URL

2024-07-07 13:17:14
Error   
scrapeSceneURL: input: scrapeSceneURL Internal system error. Error <runtime error: index out of range [0] with length 0>
2024-07-07 13:17:14
Error   
runtime error: index out of range [0] with length 0

I get that message when clicking the URL button

![image](https://github.com/stashapp/CommunityScrapers/assets/33134502/5e3306f1-c530-4901-987e-794ea18fde4e)

If I click Scrape with Pornhub, it says no scenes found.

if the image isn't allowed let me know

**Comment by feederbox826** [comment]
Cannot repro - The "Scrape With" (Blue) checks against the filename for a yt-dlp filename format `(ph5ea1d4d610917.mp4)` Are you sure you're not in a location where [PornHub requires age verification](https://www.pornhub.com/blog/age-verification-in-the-news) ?

**Comment by Maista6969** [comment]
Unable to reproduce this either, please check the age verification issue :)
