### ISSUE TITLE
pmvhaven scraper issues

### ISSUE THREAD

**Issue by 4cz36sae** [stashapp/CommunityScrapers#1934]
attempting to scrape a scene from the url (https://pmvhaven.com/video/Corrupted-by-your-Girlfriend-s-Sister-Binaural-Story-Audio_668fd90390c393c83960a0ae) though I seem to get the same issue with a few other urls as well. Also tried scrapeSingleScene  with no luck, making me think I missed something, any insights to the below error logs would be appreciated. Running stash as a container (v0.26.2)

by url 

`024-07-11 23:19:08
Error   
scrapeSceneURL: input: scrapeSceneURL could not unmarshal json from script output: EOF
2024-07-11 23:19:08
Error   
could not unmarshal json from script output: EOF
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven]     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven] requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven]   File "/usr/lib/python3.12/site-packages/requests/models.py", line 975, in json
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven]            ^^^^^^^^^^
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven]     return req.json()
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven]   File "/root/.stash/scrapers/community/PMVHaven/PMVHaven.py", line 27, in getData
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven]            ^^^^^^^^^^^^^^^^
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven]     data = getData(sceneId)
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven]   File "/root/.stash/scrapers/community/PMVHaven/PMVHaven.py", line 54, in getVideoById
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven]            ^^^^^^^^^^^^^^^^^^^^^
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven]     data = getVideoById(sceneId)
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven]     print(json.dumps(sceneByURL(params)))
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven]                      ^^^^^^^^^^^^^^^^^^
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven]   File "/root/.stash/scrapers/community/PMVHaven/PMVHaven.py", line 126, in sceneByURL
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven] Traceback (most recent call last):
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven]   File "/root/.stash/scrapers/community/PMVHaven/PMVHaven.py", line 137, in <module>
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven] During handling of the above exception, another exception occurred:
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven] json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven]     raise JSONDecodeError("Expecting value", s, err.value) from None
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven]   File "/usr/lib/python3.12/json/decoder.py", line 355, in raw_decode
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven]     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven]   File "/usr/lib/python3.12/json/decoder.py", line 337, in decode
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven]            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven]     return _default_decoder.decode(s)
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven]   File "/usr/lib/python3.12/json/__init__.py", line 346, in loads
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven]     return complexjson.loads(self.text, **kwargs)
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven] Traceback (most recent call last):
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven]   File "/usr/lib/python3.12/site-packages/requests/models.py", line 971, in json`

by scene 
`24-07-11 23:21:21
Error   
scrapeSingleScene: input: scrapeSingleScene scraper PMVHaven: could not unmarshal json from script output: EOF
2024-07-11 23:21:21
Error   
could not unmarshal json from script output: EOF
2024-07-11 23:21:21
Error   
[Scrape / PMVHaven] Did not find ID from video title Corrupted by your Girlfriend's Sister - Binaural Story Audio.mp4
2024-07-11 23:19:08
Error   
scrapeSceneURL: input: scrapeSceneURL could not unmarshal json from script output: EOF
2024-07-11 23:19:08
Error   
could not unmarshal json from script output: EOF
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven]     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven] requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven]   File "/usr/lib/python3.12/site-packages/requests/models.py", line 975, in json
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven]            ^^^^^^^^^^
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven]     return req.json()
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven]   File "/root/.stash/scrapers/community/PMVHaven/PMVHaven.py", line 27, in getData
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven]            ^^^^^^^^^^^^^^^^
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven]     data = getData(sceneId)
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven]   File "/root/.stash/scrapers/community/PMVHaven/PMVHaven.py", line 54, in getVideoById
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven]            ^^^^^^^^^^^^^^^^^^^^^
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven]     data = getVideoById(sceneId)
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven]     print(json.dumps(sceneByURL(params)))
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven]                      ^^^^^^^^^^^^^^^^^^
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven]   File "/root/.stash/scrapers/community/PMVHaven/PMVHaven.py", line 126, in sceneByURL
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven] Traceback (most recent call last):
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven]   File "/root/.stash/scrapers/community/PMVHaven/PMVHaven.py", line 137, in <module>
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven] During handling of the above exception, another exception occurred:
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven] json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven]     raise JSONDecodeError("Expecting value", s, err.value) from None
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven]   File "/usr/lib/python3.12/json/decoder.py", line 355, in raw_decode
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven]     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven]   File "/usr/lib/python3.12/json/decoder.py", line 337, in decode
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven]            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven]     return _default_decoder.decode(s)
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven]   File "/usr/lib/python3.12/json/__init__.py", line 346, in loads
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven]     return complexjson.loads(self.text, **kwargs)
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven] Traceback (most recent call last):
2024-07-11 23:19:08
Error   
[Scrape / PMVHaven]   File "/usr/lib/python3.12/site-packages/requests/models.py", line 971, in json`

**Comment by TinyAtoms** [comment]
Sometimes the creator is not present in the API response.
I suggest the following fix to line 66 of the current PMVhaven scraper:
instead of `"studio": video["creator"]`, use`"studio": {"Name": video.get("creator", None) or video.get("uploader")},`

**Comment by DogmaDragon** [comment]
@TinyAtoms uploader and creator have very different meanings there. Creator or is the author of the content, while uploader can be anyone. I don't think the proposed change makes sense from metadata perspective. 

You can make the change locally.

**Comment by TinyAtoms** [comment]
but it still needs ammendment. If no creator is provided by the api it errors out. Assign None or something if the key is not present.
```
2024-10-07 23:56:13
Error   
scrapeSceneURL: input: scrapeSceneURL could not unmarshal json from script output: EOF
2024-10-07 23:56:13
Error   
could not unmarshal json from script output: EOF
2024-10-07 23:56:13
Error   
[Scrape / PMVHaven] KeyError: 'creator'
2024-10-07 23:56:13
Error   
[Scrape / PMVHaven]                        ~~~~~^^^^^^^^^^^
2024-10-07 23:56:13
Error   
[Scrape / PMVHaven]     "studio": {"Name": video["creator"]},
2024-10-07 23:56:13
Error   
[Scrape / PMVHaven]   File "/config/scrapers/community/PMVHaven/PMVHaven.py", line 71, in getVideoById
2024-10-07 23:56:13
Error   
[Scrape / PMVHaven]            ^^^^^^^^^^^^^^^^^^^^^
2024-10-07 23:56:13
Error   
[Scrape / PMVHaven]     data = getVideoById(sceneId)
2024-10-07 23:56:13
Error   
[Scrape / PMVHaven]   File "/config/scrapers/community/PMVHaven/PMVHaven.py", line 122, in sceneByURL
2024-10-07 23:56:13
Error   
[Scrape / PMVHaven]                      ^^^^^^^^^^^^^^^^^^
2024-10-07 23:56:13
Error   
[Scrape / PMVHaven]     print(json.dumps(sceneByURL(params)))
2024-10-07 23:56:13
Error   
[Scrape / PMVHaven]   File "/config/scrapers/community/PMVHaven/PMVHaven.py", line 132, in <module>
2024-10-07 23:56:13
Error   
[Scrape / PMVHaven] Traceback (most recent call last):
```
