### ISSUE TITLE
FratX Scraper

### ISSUE THREAD

**Issue by ghotso** [stashapp/CommunityScrapers#1975]
Are you scraping a scene, gallery, movie, or performer? `-- Scene`
Scrape with URL? If so, what URLs have you tried?  `-- Yes: https://fratx.com/trailer.php?id=369`

Please check the logs to see if there are any relevant error messages you can include. `-- Cannot scrape at all, as the base URL of FratX.com is as above and not as mentioned in FratX.py like https://fratx.com/episode/`

Would be awesome if someone could fix this. Thanks in advance :)

**Comment by Maista6969** [comment]
Thank you for reporting this, I've updated the scraper for their new site layout 🙂 Unfortunately they removed their `episode/title-slug` style URLs so we've lost the ability to scrape by fragment, but on the bright side the scraper no longer requires Python
