### ISSUE TITLE
shesfreaky.com

### ISSUE THREAD

**Issue by incognito-bb** [stashapp/CommunityScrapers#2001]
## Notes

I'd ideally like this to scrape
- Title
- URL
- Thumbnail
- tags
- Description
- Date

This should not scrape
- Studio
- Performer

### URLs that you would expect to scrape

[Scene example URL](https://www.shesfreaky.com/video/random-clip-20264-1000344.html)

### YT-DLP Filename with default Settings
`Random Clip 20264 - ShesFreaky (1) [random-clip-20264-1000344-1].mp4`

**Comment by feederbox826** [comment]
working on it
