### ISSUE TITLE
Hanime Scraper issues

### ISSUE THREAD

**Issue by MarkasDaemon** [stashapp/CommunityScrapers#2021]
When I try to scrap any hentai metadata with "Hanime" it always returns with this error 
" { scrapper hanime : discipline 1 ": EOF  } "
I was trying to scrap a hen*ai scene call " Discipline " a

I need a fix for this or let me know which scrapper is best for hen*ai scraping

**Comment by feederbox826** [comment]
can you provide a link

**Comment by MarkasDaemon** [comment]
> can you provide a link

Sorry i didn't understand.. Which link? I tried to use it in scene scraping..

**Comment by DogmaDragon** [comment]
> Which link?

The example of the link you tried to scrape.

**Comment by MarkasDaemon** [comment]
> > Which link?
> 
> The example of the link you tried to scrape.

![Uploading Screenshot_2024-09-12-21-26-21-77_40deb401b9ffe8e1df2f1cc5ba480b12.jpg…]()

**Comment by MarkasDaemon** [comment]
![Screenshot_2024-09-12-21-26-43-05_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/83a7face-cf7f-41ce-989d-9e1c018600ed)
![Screenshot_2024-09-12-21-27-30-63_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/8bd1a9be-b74e-45a0-9405-97330b30358e)

**Comment by MarkasDaemon** [comment]
![Uploading Screenshot_2024-09-12-21-26-21-77_40deb401b9ffe8e1df2f1cc5ba480b12.jpg…]()

**Comment by MarkasDaemon** [comment]
![IMG_20240912_234232](https://github.com/user-attachments/assets/a3e47326-f83c-4b72-880f-9b35250d31f6)
I was talking about this 🥹

**Comment by feederbox826** [comment]
The link your screenshot links to is invalid because the video does not exist. In order to match with the fragment scraper, your filname has to match exactly. In this case, `nocturnal-1`, instead of `noctural- 1` paste the URL (`https://hanime.tv/videos/hentai/nocturnal-1`) to avoid the stringent checks

**Comment by MarkasDaemon** [comment]
I did as u said.. result is same error.

https://github.com/user-attachments/assets/abf17acf-022e-4cc2-b058-48a586df86f0

. can u please give a video or ss how u do scrap hentai?

**Comment by feederbox826** [comment]
try using a VPN or posting your logs, it sounds like your connection might be slow or blocked

**Comment by MarkasDaemon** [comment]
![Screenshot_2024-09-13-09-30-21-35_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/3a8db021-a82a-49c7-992e-cdee465ee743)
Log 🥺
