### ISSUE TITLE
Traxxx is broken

### ISSUE THREAD

**Issue by Kev1n121** [stashapp/CommunityScrapers#2029]
2024-09-15 14:56:21
Error   
scrapeSceneURL: input: scrapeSceneURL could not unmarshal json from script output: EOF
2024-09-15 14:56:21
Error   
could not unmarshal json from script output: EOF
2024-09-15 14:56:21
Error   
[Scrape / Traxxx] HTTP Error 401, Unauthorized. Cookie authentication most likely failed
2024-09-15 14:56:20
Info    
[Scrape / Traxxx] scene_url

I am getting this error, When trying scraping with Traxxx. Is there a way to fix this?

**Comment by feederbox826** [comment]
looks like traxxx added authentication or CF got more aggressive

**Comment by feederbox826** [comment]
Looks like traxxx migrated, will force this one over to old.traxxx
