### ISSUE TITLE
IAFD - Not working after update to the lastest Stash and Update Scrappers through UI interface

### ISSUE THREAD

**Issue by pthanhtu92** [stashapp/CommunityScrapers#2044]
I get this error while running IAFD Scrapper on a scene. 
`ERRO[2024-09-27 00:12:01] [Scrape / IAFD] HTTP Error: 403, giving up
ERRO[2024-09-27 00:12:01] could not unmarshal json from script output: EOF
ERRO[2024-09-27 00:12:01] scrapeSceneURL: input: scrapeSceneURL could not unmarshal json from script output: EOF
2024-09-27T00:12:01.4325215-04:00 INF Response: 200 OK httpRequest={"proto":"HTTP/1.1","remoteIP":"127.0.0.1:58050","requestID":"Bee/GkmWokit4u-001768","requestMethod":"POST","requestPath":"/graphql","requestURL":"https://127.0.0.1:9999/graphql"} httpResponse={"bytes":130,"elapsed":30898.2765,"status":200} service=stash`

I tried to re-scrape a scene that previously scraped successfully before the update, but the same error happened

**Comment by feederbox826** [comment]
403 means request unauthorized, that usually means cloudflare or region restriction. Can you send a link to test? otherwise, you might need a VPN

**Comment by pthanhtu92** [comment]
It did the same with performer scrape. I use this [https://www.iafd.com/person.rme/perfid=ajapplegate/gender=f/a.j.-applegate.htm](https://www.iafd.com/person.rme/perfid=ajapplegate/gender=f/a.j.-applegate.htm). The error is `2024-09-27 00:47:57Error   scrapePerformerURL: input: scrapePerformerURL could not unmarshal json from script output: EOF
2024-09-27 00:47:57Error   could not unmarshal json from script output: EOF
2024-09-27 00:47:57Error   [Scrape / IAFD] HTTP Error: 403`

**Comment by feederbox826** [comment]
Works for me, 
![image](https://github.com/user-attachments/assets/2d406635-9fe6-4e12-8ada-cd0cbbb4eef6)

You might need a VPN as it sounds like IAFD is blocked

**Comment by pthanhtu92** [comment]
Do you have any recommend VPN? I used NordVPN and same error happened.

**Comment by pthanhtu92** [comment]
I got it worked on PIA. Thank you. Is there a way integrate proxy in to IAFD.py?

**Comment by DogmaDragon** [comment]
@pthanhtu92 you can proxy the whole Stash by setting it in the config.yml file See https://docs.stashapp.cc/in-app-manual/configuration/#advanced-configuration-options

**Comment by pthanhtu92** [comment]
Thank you!
