### ISSUE TITLE
GayAdultEmpire not Scraping URL or Search

### ISSUE THREAD

**Issue by AbyssDarkVoid** [stashapp/CommunityScrapers#2071]
GayAdultEmpire not working after latest website update. It looks like within the past day or so GayAdultEmpire updated their website. Now when you first go to the website, it prompts you to acknowledge you are over the age of 18. I believe this change broke the scraper.

_Are you scraping a scene, gallery, movie, or performer?_ Scene
_Scrape with URL? If so, what URLs have you tried?_  
https://www.gaydvdempire.com/3292406/bareback-hammers-porn-videos.html

Scraping with both URL and Search 
_Scrape with fragment? If so, what is the filename / title / studio code?_  
_Scrape with name? Give an example you searched for that caused the scraper to fail_ Bareback Hunters (2022)
Searched: Bareback Hammers (2022)

Search Error:
2024-10-19 16:30:00Error   scrapeSingleScene: input: scrapeSingleScene error while name scraping with scraper GayAdultEmpire: Get "https://www.gaydvdempire.com:80/AgeConfirmation?url2=/vod/search?q=Bareback+Hammers+%282022%29": http: server gave HTTP response to HTTPS client

Please check the logs to see if there are any relevant error messages you can include

Error from attempt to scrape URL:
2024-10-19 16:27:47Error   scrapeSceneURL: input: scrapeSceneURL Get "https://www.gaydvdempire.com:80/AgeConfirmation?url2=/3292406/bareback-hammers-porn-videos.html": http: server gave HTTP response to HTTPS client

**Comment by andbigdata** [comment]
AdultEmpire and Elegant Angel which appear to use similar scrapers to GayAdultEmpire are also broken with the same issue. Both scene and movie scraping impacted, but not sure about other types.


Scene URLs I've tried recently.
https://www.elegantangel.com/shop/1669951/elegant-angel-kimmy-kimm-just-wanted-a-man-who-would-take-charge-streaming-scene-video.html

https://www.adultempire.com/4761040/married-woman-15-a-porn-videos.html

**Comment by feederbox826** [comment]
This is state-based age verification

https://www.adultdvdempire.com/AgeVerification

Stash has no way to bypass this, you'll need to set up a proxy or VPN for your stash container
