### ISSUE TITLE
ColbyKnox Scraper not scraping URLs - Gives Failed to Verify Certificate Error

### ISSUE THREAD

**Issue by AbyssDarkVoid** [stashapp/CommunityScrapers#2075]
I am trying to scrape a scene using a URL this: https://colbyknox.com/videos/bed-head and am receiving an error message that says: 

Get "https://colbyknox.com/videos/bed-head": tls: failed to verify certificate: x509: certificate signed by unknown authority

2024-10-23 15:22:19Error   scrapeSceneURL: input: scrapeSceneURL Get "https://colbyknox.com/videos/bed-head": tls: failed to verify certificate: x509: certificate signed by unknown authority

Thanks in advance!

**Comment by feederbox826** [comment]
This is an issue on their site

https://www.ssllabs.com/ssltest/analyze.html?d=colbyknox.com&hideResults=on

they did not properly chain their certificates and golang has no way to bypass it in environment variables :/

**Comment by WellDoneLiz** [comment]
Certificate renewed, scraper is working.
