### ISSUE TITLE
Falcon / Algolia Scene Scraper Failing 

### ISSUE THREAD

**Issue by departure18** [stashapp/CommunityScrapers#2088]
When i try to scrape a Falcon / Algolia scraper by url if fails with a could not unmarshal json error. The logs show another error:
`[Scrape / Falcon Studios] requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=9999): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000279CE980C20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))`

I checked the scraper with a scene from Wicked (Also Algolia) and it fails in the same fashion.

Weirdly the movie / group scraper is working for me.

The full log is below:

024-11-03 21:06:05
Error   
scrapeSceneURL: input: scrapeSceneURL could not unmarshal json from script output: EOF
2024-11-03 21:06:05
Error   
could not unmarshal json from script output: EOF
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios] requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=9999): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000279CE980C20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]     raise ConnectionError(e, request=request)
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]   File "C:\interp\Python313\Lib\site-packages\requests\adapters.py", line 700, in send
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]     r = adapter.send(request, **kwargs)
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]   File "C:\interp\Python313\Lib\site-packages\requests\sessions.py", line 703, in send
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]     resp = self.send(prep, **send_kwargs)
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]   File "C:\interp\Python313\Lib\site-packages\requests\sessions.py", line 589, in request
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]            ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]     return session.request(method=method, url=url, **kwargs)
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]   File "C:\interp\Python313\Lib\site-packages\requests\api.py", line 59, in request
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]     return request("post", url, data=data, json=json, **kwargs)
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]   File "C:\interp\Python313\Lib\site-packages\requests\api.py", line 115, in post
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]     response = requests.post(stash_url, json=json, headers=headers)
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]   File "C:\Users\steve\.stash\scrapers\community\py_common\graphql.py", line 41, in callGraphQL
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]              ~~~~~~~~~~~^^^^^^^
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]     result = callGraphQL(query) or {}
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]   File "C:\Users\steve\.stash\scrapers\community\py_common\graphql.py", line 243, in configuration
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]     stash_config = graphql.configuration()
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]   File "C:\Users\steve\.stash\scrapers\community\Algolia\Algolia.py", line 879, in <module>
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios] Traceback (most recent call last):
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios] During handling of the above exception, another exception occurred:
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios] urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=9999): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000279CE980C20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]   File "C:\interp\Python313\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]     )
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]         method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]     retries = retries.increment(
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]   File "C:\interp\Python313\Lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]     )
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]         chunked=chunked,
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]     ...<9 lines>...
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]         method=request.method,
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]     resp = conn.urlopen(
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]   File "C:\interp\Python313\Lib\site-packages\requests\adapters.py", line 667, in send
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios] Traceback (most recent call last):
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios] The above exception was the direct cause of the following exception:
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios] urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000279CE980C20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]     ) from e
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]         self, f"Failed to establish a new connection: {e}"
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]     raise NewConnectionError(
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]   File "C:\interp\Python313\Lib\site-packages\urllib3\connection.py", line 214, in _new_conn
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]                 ~~~~~~~~~~~~~~^^
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]     self.sock = self._new_conn()
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]   File "C:\interp\Python313\Lib\site-packages\urllib3\connection.py", line 279, in connect
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]     ~~~~~~~~~~~~^^
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]     self.connect()
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]   File "C:\interp\Python313\Lib\http\client.py", line 1035, in send
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]     ~~~~~~~~~^^^^^
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]     self.send(msg)
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]   File "C:\interp\Python313\Lib\http\client.py", line 1091, in _send_output
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]     ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]     self._send_output(message_body, encode_chunked=encode_chunked)
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]   File "C:\interp\Python313\Lib\http\client.py", line 1331, in endheaders
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]     ~~~~~~~~~~~~~~~^^
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]     self.endheaders()
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]   File "C:\interp\Python313\Lib\site-packages\urllib3\connection.py", line 441, in request
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]     ^
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]     )
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]         enforce_content_length=enforce_content_length,
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]     ...<6 lines>...
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]         ^^^^^^^
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]         method,
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]     ~~~~~~~~~~~~^
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]     conn.request(
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]   File "C:\interp\Python313\Lib\site-packages\urllib3\connectionpool.py", line 495, in _make_request
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]     )
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]         **response_kw,
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]     ...<10 lines>...
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]         conn,
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]     response = self._make_request(
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]   File "C:\interp\Python313\Lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios] Traceback (most recent call last):
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios] The above exception was the direct cause of the following exception:
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios] ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]     ~~~~~~~~~~~~^^^^
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]     sock.connect(sa)
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]   File "C:\interp\Python313\Lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]     raise err
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]   File "C:\interp\Python313\Lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]     )
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]         socket_options=self.socket_options,
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]     ...<2 lines>...
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]         (self._dns_host, self.port),
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]     sock = connection.create_connection(
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios]   File "C:\interp\Python313\Lib\site-packages\urllib3\connection.py", line 199, in _new_conn
2024-11-03 21:06:05
Error   
[Scrape / Falcon Studios] Traceback (most recent call last):
2024-11-03 21:06:01
Debug   
[Scrape / Falcon Studios] URL Scraping: https://members.falconstudios.com/en/video/falconstudios/Knockout/20925
2024-11-03 21:06:01
Info    
[Scrape / Falcon Studios] URL Domain: members.falconstudios
2024-11-03 21:06:01
Info    
[Scrape / Falcon Studios] New API keys: YWNmZjljMDM0YThkZGIwZmQ5Mzc1ZjkzNjcwN2E5NzVmOWVmMzg4NDk4YzI1NGUzNjI4Y2FlZGVlMzQzYzdhOXZhbGlkVW50aWw9MTczMDY3ODc2MiZyZXN0cmljdEluZGljZXM9YWxsJTJBJmZpbHRlcnM9c2VnbWVudCUzQWZhbGNvbnN0dWRpb3M=
2024-11-03 21:06:01
Debug   
[Scrape / Falcon Studios] Writing config!
2024-11-03 21:05:59
Debug   
[Scrape / Falcon Studios] Request URL: https://www.falconstudios.com/en
2024-11-03 21:05:59
Info    
[Scrape / Falcon Studios] Need new api key: [21|20|0]
2024-11-03 21:05:59
Debug   
[Scrape / Falcon Studios] Config Path: C:\Users\steve\.stash\config.yml
2024-11-03 21:05:59
Debug   
[Scrape / Falcon Studios] [py_common\graphql.py] Reading config from C:\Users\steve\.stash\scrapers\community\py_common\config.ini
2024-11-03 21:05:58
Debug   
Scraper script <C:\interp\Python313\python.exe ../Algolia/Algolia.py falconstudios> started

**Comment by Maista6969** [comment]
This appears to be failing because it's trying to connect to your local Stash and you're running on a non-standard port, or perhaps behind a firewall: try updating the configuration in `C:\Users\steve.stash\scrapers\community\py_common\config.ini`

**Comment by departure18** [comment]
Yep! That was the problem! Sorry!

**Comment by Maista6969** [comment]
Happy to help, I'll try to add a better error message for the next time :)
