### ISSUE TITLE
LetThemWatch - Add Support for Network Sites

### ISSUE THREAD

**Issue by AbyssDarkVoid** [stashapp/CommunityScrapers#2093]
Can the scraper for Let Them Watch be updated to include these sites below in its network?

UncutLatinos.com
https://uncutlatinos.com
	
UncutTwinks.com
https://uncuttwinks.com
	
UncutKing.com
https://uncutking.com
	
CumDumpVan.com
https://cumdumpvan.com/
	
HungPapi.com
https://hungpapi.com/

I am including links to a scene from each site.

Scenes:
https://uncutlatinos.com/trailers/Fuck-ME-HARD.html
https://uncuttwinks.com/trailers/Twink-Destroyed.html
https://uncutking.com/trailers/UNK005-DixtoSJaoLucas.html
https://cumdumpvan.com/trailers/Season-4-Episode-5-Brett-Fox-FOLSOM-Street-Fair-Festival-SF.html
https://hungpapi.com/trailers/Fucking-The-HOMIE.html

I am also hoping the following two additions can be made to the scraper. Ability to scrape from Models pages as well as the ability to search the site for scenes.

Example Models:
https://letthemwatch.com/models/juven.html
https://uncutlatinos.com/models/Solomon.html
https://uncuttwinks.com/models/JayMagnus.html
https://uncutking.com/models/Dixto.html
https://cumdumpvan.com/models/BrettFox.html
https://hungpapi.com/models/AzaelMaluma.html

**Comment by MortonBridges** [comment]
PR #2097 checked in to handle the additional sites for the sceneByURL scrapers.

Performer scraping, while possible, will be difficult, as the model entries don't follow a simple, clear, consistent format for info (penis length and characteristics for example).  It's going to take a bit more effort than I can dedicate currently to make this happen if I'm going to do it properly.
