### ISSUE TITLE
GayAdultEmpire - Scraping incorrect data from individual scenes

### ISSUE THREAD

**Issue by AbyssDarkVoid** [stashapp/CommunityScrapers#2099]
Trying to scrape a scene from a movie.

The scene is linked here: https://www.gaydvdempire.com/clip/836895/scene-2-streaming-scene.html

When I try to scrape the URL, it is trying to pull in Protein Shake as the Studio name rather than Trailer Trash Boys for the Studio.

It's also wanting to pull in Scene 2 or Scene 2 from Protein Shake when it should be pulling in the group name of Protein Shake.

This is the link to the actual movie on GayAdultEmpire.

https://www.gaydvdempire.com/3190601/protein-shake-porn-videos.html

If I try and scrape that URL as a new scene, it will populate the information correctly

No error messages to share.

**Comment by MortonBridges** [comment]
#2102 created for this issue.
