### ISSUE TITLE
BlurredMedia Issue

### ISSUE THREAD

**Issue by SailorSilly** [stashapp/CommunityScrapers#2106]
Trying to scrape a scene with this URL here: https://www.gayhoopla.com/video/superstars-meet-channing-rodd-fucks-jayden-marcos

Error message on screen is: Internal system error. Error <runtime error: index out of range [0] with length 0>

From Logs:

2024-11-14 17:48:26Error   scrapeSceneURL: input: scrapeSceneURL Internal system error. Error <runtime error: index out of range [0] with length 0>
2024-11-14 17:48:26Error   runtime error: index out of range [0] with length 0

**Comment by Maista6969** [comment]
I am unable to reproduce this, are you scraping from a location that might be geoblocking?

![image](https://github.com/user-attachments/assets/337b8f6a-7dd2-4a10-a103-1607c9d8a551)

**Comment by MortonBridges** [comment]
The error was happening on my Stash before I upgraded the scraper to version 447d45d.  Recommend @SailorSilly upgrade if they haven't already.
