### ISSUE TITLE
Scrapers Request: heatwavepass.com

### ISSUE THREAD

**Issue by xiosensei** [stashapp/CommunityScrapers#2111]
### URLs that you would expect to scrape

[Performer example URL](http://www.heatwavepass.com/pornstars/sophie-dee.html-4632)
[Scene example URL](http://www.heatwavepass.com/scenes/fishnet-covered-blond-tasting-chocolate-59842.html)
[Movie example URL](http://www.heatwavepass.com/dvds/black-balled-7-5766.html)

**Comment by xiosensei** [comment]
@WellDoneLiz somehow I am getting json error when scraping this: https://www.heatwavepass.com/scenes/double-penetration-turns-into-a-bust-63855.html

**Comment by feederbox826** [comment]
resolved by #2114, if you have problems with the scraper, please open a new issue
