### ISSUE TITLE
Adult Empire "Show More" in synopsis

### ISSUE THREAD

**Issue by steff2632** [stashapp/CommunityScrapers#2116]
How could the scraper be better?

When scraping the synopsis pulls in the text for the "show more" & "show less" buttons

![Screenshot 2024-11-21 at 11 04 35 pm](https://github.com/user-attachments/assets/55a66b04-1229-4a1a-a141-ff22d15d8aa7)

the webpage has those buttons in a div called `synopsis-content__actions` and the scrapper appears to be grabbing all divs that contain the words `synopsis-content` and concatenating them.
![Screenshot 2024-11-21 at 11 05 09 pm](https://github.com/user-attachments/assets/852530cb-42c5-4bf1-9394-666199c7cb72)

should change from a "contains" to an "exact" match if possible

**Comment by steff2632** [comment]
this change doesn't seem to be working? It's still pulling in the more/less buttons

**Comment by feederbox826** [comment]
It worked on the links I tested, send the offending links

**Comment by steff2632** [comment]
Seems like some work

https://www.adultdvdempire.com/1716265/i-love-my-sisters-big-tits-3-porn-movies.html works but 
https://www.adultdvdempire.com/1723386/i-love-my-sisters-big-tits-4-porn-movies.html adds the texts

**Comment by Maista6969** [comment]
Thank you for those examples! I have pushed a fix in 8119079 that I've also tested on [Pirates](https://www.adultempire.com/700215/pirates-porn-movies.html) to make sure it works with movies where the description spans across multiple elements
