### ISSUE TITLE
TeamSkeetAPI - add support for member link

### ISSUE THREAD

**Issue by Gyvari060104** [stashapp/CommunityScrapers#2122]
add support for teamskeet and mylf member link so can scrape using
app.teamskeet.com and app.mylf.com
because some of older scene is not having any public link anymore

**Comment by feederbox826** [comment]
Do you have any examples of members-only links?

**Comment by feederbox826** [comment]
One example of a broken link was 

`https://www.analmom.com/movies/mending-a-broken-heart-1`
`https://www.teamskeet.com/movies/mending-a-broken-heart` (wrong scene)
`https://app.teamskeet.com/movies/27847?r=`
