### ISSUE TITLE
[py_common] Improve compatibility with older python versions

### ISSUE THREAD

**Issue by estellaarrieta** [stashapp/CommunityScrapers#2125]
https://github.com/stashapp/CommunityScrapers/blob/master/scrapers/py_common/types.py
```
from typing import Literal, Required, TypedDict
```

`Required` was introduced in Python 3.11, this is the single file that breaks compatibility with older versions.
One of the ways to solve it would be to use https://github.com/python/typing_extensions

**Comment by feederbox826** [comment]
3.11 was EOL'd on 2024-04-01 and we test against newest stable. Since it's relatively static, I would recommend you make the changes locally instead

**Comment by feederbox826** [comment]
Since this is a backport, this would break on newer installs, because it's provided by the system python. Instead, make this change on your local installations.
