### ISSUE TITLE
[Bug] [iafd.com] Scraper 

### ISSUE THREAD

**Issue by hassaffe** [stashapp/CommunityScrapers#283]
Performer scrapers

If you are looking for an actress and the performer scrapers. If there are several actresses with the same name, several names are displayed in the list. But no matter which entry in the list you select, the same actress is always loaded.

Desktop (please complete the following information):

    OS: Linux
    Browser Firefox, Chrome

![99297856-1e3d7580-2849-11eb-9010-e72451b338bd](https://user-images.githubusercontent.com/55273555/99819932-68c43800-2b50-11eb-8048-e74f0fb4ce8a.jpg)

**Comment by bnkai** [comment]
![2020-11-20_200450](https://user-images.githubusercontent.com/48220860/99834165-d336a180-2b6b-11eb-893e-664bee87ecf9.png)
@hassaffe it seems to work for me. Can anyone else verify this ?
can you double check that you have latest scraper for iafd ? date at the end of the scraper files shoud be 
```bash
# Last Updated November 8, 2020
```
do you use stable or dev version of stash?

**Comment by hassaffe** [comment]
yes downloaded again today. At iafd.com, the name appears several times with different presentation channels. But he always loads the profile of the same actress in Stash.

**Comment by bnkai** [comment]
Nvm i just realised that you meant. It seems to be a bug with stash. For the time being for those performers you have to add the url and do a scrape by url.

**Comment by bnkai** [comment]
The original https://github.com/stashapp/stash/issues/944 issue seems to be a better place for this as the bug was verified. Closing this one.
