### ISSUE TITLE
Feature Request: Add Support for plex

### ISSUE THREAD

**Issue by Animizio** [stashapp/CommunityScrapers#413]
Hey, I would love to use that scrapers with my plex server. maybe as an organizer before adding it to plex and/or use an metadata agent in plex with that scrapers. Maybe someone wants it too and have some time for it. I really would love that feature for my plex. thanks!

**Comment by bnkai** [comment]
These scrapers need stash to work. I think apart from using the xPaths or using part of the scripts there is nothing else you can do with them and plex. The focus here is on integration with stash not generic scrapers. <https://github.com/PAhelper/PhoenixAdult.bundle> should be what you need

**Comment by bnkai** [comment]
<https://github.com/stashapp/CommunityScripts/tree/main/3rd%20party/StashPlexAgent.bundle> is available and should cover this issue. Closing this but feel free to open a new issue if the plugin mentioned isnt enough.
