### ISSUE TITLE
Gamma scraper should parse out more HTML.

### ISSUE THREAD

**Issue by jeremymeyers** [stashapp/CommunityScrapers#494]
as per https://github.com/stashapp/stash/issues/1333 , Gamma sites will sometimes use HTML other than just line breaks, which get pulled into Stash which then will not render them.  Adding additional filters will address this.

**Comment by bnkai** [comment]
I have already created a  PR for the <strong> part. if you have anything else that needs to be replaced paste it (or the scene  URL) here  or in  the relevant PR <https://github.com/stashapp/CommunityScrapers/pull/493>
I looked a few scenes in random but couldnt notice anything else.

**Comment by bnkai** [comment]
Closing as relevant PR was merged.
