### ISSUE TITLE
Scraper location

### ISSUE THREAD

**Issue by TheRxLord** [stashapp/CommunityScrapers#510]
Having an issue where the community scrapers are not showing up under the Web Qui. I have moved the .yml files to the \\TOWER\cache\appdata\stash\scrapers directory. Am I doing something wrong?

**Comment by bnkai** [comment]
Is ` \TOWER\cache\appdata\stash` where the config.yml is ? If yes then the location is correct.
Not showing in api you mean here <http://localhost:9999/settings?tab=scrapers> ? (for localhost:9999 edit according to your config)

**Comment by TheRxLord** [comment]
The config.yml is located in \Tower\cache\appdata\stash\config folder.

**Comment by TheRxLord** [comment]
Correct not showing in thee  http://localhost:9999/settings?tab=scrapers of the GUI.

**Comment by bnkai** [comment]
> The config.yml is located in \Tower\cache\appdata\stash\config folder.

then the scrapers folder should be created there and the scraper files added there.
`\Tower\cache\appdata\stash\config\scrapers`
If you want to use a custom scraper folder instead you would need to edit the config.yml <https://github.com/stashapp/stash/wiki/Advanced-Configuration-Options>

**Comment by TheRxLord** [comment]
That was it. Thanks!
