### ISSUE TITLE
House of Gord scraper returns 403

### ISSUE THREAD

**Issue by quirkyjoe** [stashapp/CommunityScrapers#634]
Attempting to use the House of Gord scraper returns a 403 error in the error popup.

Example URL: https://www.houseofgord.com/d/another-naked-pussy-walker

Result:
```
Error
http error 403:Forbidden
```

**Comment by JaseNZC** [comment]
> Attempting to use the House of Gord scraper returns a 403 error in the error popup.
> 
> Example URL: https://www.houseofgord.com/d/another-naked-pussy-walker
> 
> Result:
> 
> ```
> Error
> http error 403:Forbidden
> ```

I have created a Pull Request for it here if you wanted to try it. #635

**Comment by quirkyjoe** [comment]
After replacing my current yml file and restarting Stash, trying to scrape yields the following:

![image](https://user-images.githubusercontent.com/85048415/125006735-5a2e8080-e04e-11eb-901b-8be0b7326315.png)

```
Error

exec: "google-chrome": executable file not found in $PATH
```

I don't _think_ this is on my end, because I have successfully used other scrapers on the two machines I tested the fix on. (?)

Thank you very much for your time! If I can provide any further info, let me know.

**Comment by JaseNZC** [comment]
> After replacing my current yml file and restarting Stash, trying to scrape yields the following:
> 
> ![image](https://user-images.githubusercontent.com/85048415/125006735-5a2e8080-e04e-11eb-901b-8be0b7326315.png)
> 
> ```
> Error
> 
> exec: "google-chrome": executable file not found in $PATH
> ```
> 
> I don't _think_ this is on my end, because I have successfully used other scrapers on the two machines I tested the fix on. (?)
> 
> Thank you very much for your time! If I can provide any further info, let me know.

You need to have CDP enabled for the updated yml to work :-)

Under Settings->Configuration you will see the setting to populate.

The one here is my setup as I use docker so yours will be different depending on what operating system you are using for stash.
Ie say for windows would be something like.
`c:\Program Files\Google\Chrome\Application\chrome.exe`

<img width="1148" alt="Screen Shot 2021-07-09 at 3 38 27 PM" src="https://user-images.githubusercontent.com/64925341/125019868-d87d3800-e0cb-11eb-9d88-fc2bff513544.png">

**Comment by Ruthalas** [comment]
I'm also running Stash in a docker, would you mind pointing me at the chrome docker you're using?

**Comment by JaseNZC** [comment]
command for installing headless chrome docker instance is, this is just done via terminal.
`docker run --restart=always -d -p 9222:9222 --name headless-shell --shm-size 2G chromedp/headless-shell`

**Comment by Ruthalas** [comment]
That worked perfectly. Looks great!

(Thank you for the guidance regarding the CDP path setting!)

**Comment by quirkyjoe** [comment]
That worked great, looks good!

Thank you for the guidance on the CDP path setting as well.

**Comment by bnkai** [comment]
closing this as #635 was merged
