### ISSUE TITLE
Scraper does not open 

### ISSUE THREAD

**Issue by Alexisback** [stashapp/CommunityScrapers#676]
I state that I put the scrapers in the "scrapers" folder, restarted the program, they are present

![sshot-1](https://user-images.githubusercontent.com/18039740/128209896-95539bf1-d6d9-490d-a212-c6b7e53b2720.png)

I go to the performer tab but from there I cannot open and view the scrapers 

![sshot-2](https://user-images.githubusercontent.com/18039740/128209956-825e34f2-1155-413d-84a6-8492768b77b8.png)

**Comment by JaseNZC** [comment]
Is there a name in the scrapers field. ??

This must be present if creating a new performer

<img width="835" alt="Screen Shot 2021-08-05 at 11 15 36 AM" src="https://user-images.githubusercontent.com/64925341/128267368-0eda4fb5-d76a-424e-a049-db7fb2631d09.png">

**Comment by Alexisback** [comment]
the name is present,

I found out where the problem is, the browser, or rather the browsers

The up tabs don't work

Firefox ESR 52.9.0 (64-bit)
Pale Moon 29.3.0 (64 bit)

work on Chrome 92

the problem is that by default I use Firefox (there are extensions that work on this version)

Pale Moon I use it in localhost for the server

can you fix the compatibility?

**Comment by JaseNZC** [comment]
Unless somebody else can offer any advice I would say that it could be a bug and you would be best to create a new issue on stash's main github branch. 
You could also mention it in discord to see if anybody else is having the same issue with the different browsers

**Comment by bnkai** [comment]
I am guessing  some things might not work with a browser that old. Using a recent firefox version (85.0.1) everything seems fine to me. If upgrading the browser is not possible i would make an issue in the main stash repo

**Comment by bnkai** [comment]
Closing as this does not seem scraper related
