### ISSUE TITLE
How to scrape blacked?

### ISSUE THREAD

**Issue by LordGardian** [stashapp/CommunityScrapers#685]
Hello, sorry if I sound very ignorant, but I am ignorant in these matters.
How can I scrape from the blacked page?
I downloaded the community scrappers pack and all the sites have worked for me so far by putting the URL in each scene.
But with Blacked or Vixen it just doesn't work, do I have to do anything else?

I can't do it with Brazzers either, researching I found out that you need something called CDP and a "Scraper User Agent".
I don't know what either is. I'm an idiot when it comes to anything programming or these things. Honestly, I just wanted to get my porn organized and on the internet I came across this program (or whatever), and found it interesting, but it requires more than I am able to give it to get the most out of it.

**Comment by peolic** [comment]
> How can I scrape from the blacked page?

To scrape the Vixen Network sites, you need to install [Python](https://www.python.org/downloads/) (any version 3.7 and above is fine) and then open command prompt (assuming Windows machine) and run `pip install -U requests`. Then you should be able to scrape.

**Comment by bnkai** [comment]
Closing as issue should be resolved
