### ISSUE TITLE
scraping clip information from dvd sites

### ISSUE THREAD

**Issue by xiosensei** [stashapp/CommunityScrapers#763]
proposing to add a way to scrape specific scenes from a movie page.

example: https://www.hotmovies.com/video/320614/Babysitting-The-Baumgartners/

I would like to scrape clip 10 to get the actors, the very specific tags that this site provides and the scene number!

one way to do it is by providing the scene id as a hashtag after the link: https://www.hotmovies.com/video/320614/Babysitting-The-Baumgartners/#2193787

but obviously this does not get picked up by the scraper and i am guessing development is needed before that part can be picked up.

another way is to maybe providing the clip number as a hashtag in the link: https://www.hotmovies.com/video/320614/Babysitting-The-Baumgartners/#10 -- to indicate I want to scrape scene 10 info.

**Comment by bnkai** [comment]
This is a very specific need and site specific i think.While not possible by json or xpath scrapers you could make a script (python?) scraper to get what you want

**Comment by philpw99** [comment]
@xiosensei 
This site is very interesting. I am trying to find a way to get info only for clip 10. If I manage to do that, I will let you know.

**Comment by philpw99** [comment]
Seems it can only be done by using python script and ask a clip number on the fly. Like a window below:
![test](https://user-images.githubusercontent.com/22040708/141717966-5a832b1c-f77e-4ee5-aed0-83703886afd1.png)

Will this dialog be ok when scraping?

**Comment by philpw99** [comment]
I chatted in Discord about this. Seems this GUI prompt is not a good idea.
Now I am wondering how to get the clip no from the user.
One way is to get the number by adding "?clip=10" in the end of the URL.
But then the user might not know about it, and wonder why the scraper doesn't work.

**Comment by philpw99** [comment]
Great ! Now the one who requested this has no more interest in this. Why should I make this scraper at all ?

**Comment by xiosensei** [comment]
@philpw99 I am here.. just gave up on this when @bnkai replied lol.

**Comment by themese8** [comment]
I have made a PR for a scraper for AdultFilmIndex, the site has metadata of thousands of adult DVDs https://github.com/stashapp/CommunityScrapers/pull/892
