### ISSUE TITLE
403 Permission Denied from virtualrealporn.com using VirtualRealPorn.yml

### ISSUE THREAD

**Issue by freeagent1384** [stashapp/CommunityScrapers#789]
When scraping from virtualrealporn.com using VirtualRealPorn.yml I receive an error "http error 403:Forbidden"

Using production docker container for Stash host with chromedp/headless-shell configured for CDP.

Doesn't appear to be scene specific but to provide an example:

https://virtualrealporn.com/vr-porn-video/the-swap-part-2/

**Comment by bnkai** [comment]
The specific scraper doesnt use CDP so thats not an issue

Try adding a user agent in the scraping settings
eg `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0)`

The scraper works fine for me with or without the user agent setting so you might got blocked from that site either for too many tries, using a vpn, geoblocking or using a blacklisted ip ( some sites/cf seem to block hetzner ip ranges and some other vps providers so if you are using a vps/remote server and not a home connection that could be it )

**Comment by freeagent1384** [comment]
Thanks bnkai, that did the trick.  Not sure why I had to add the header but I don't think it was for any of the reasons you listed.  I haven't visited the site before today and only loaded maybe 10 pages from there over several minutes, I don't use a VPN,  and I don't think geoblocking is likely based on my location.  I suppose I could have a black listed IP but this would be the first time it's been an issue.  Either way, you resolved my issue so I thank you.
