### ISSUE TITLE
Blocked Scrapers

### ISSUE THREAD

**Issue by mmenanno** [stashapp/CommunityScrapers#81]
### MGStage
**Draft PR:** _None yet_

#### Sites:
https://www.mgstage.com/

#### Why Is it blocked?:
You have the "Are you above 18 years old?" that block the page. This cookie needs to exist for the scraper to work:
![](https://user-images.githubusercontent.com/1358708/95530499-03efbc80-09ac-11eb-9714-754783078af1.png)

#### What might unblock this?:
Either the ability to set a specific cookie in a scraper, or the ability to click a site button within the scraper.

---

### Title
**Draft PR:**
#### What might unblock this?:

**Comment by bnkai** [comment]
bang.com and puretaboo can be unblocked with https://github.com/stashapp/stash/pull/625

**Comment by Belleyy** [comment]
Look like DigitalPlayground, Mofos and other from the same network (except Brazzers ATM), use javascript to load everything.

![](https://i.imgur.com/11M8oZ7.png)

**Comment by Belleyy** [comment]
### **ReidMyLips**

**PR**: Local
**Sites**: 
- reidmylips.elxcomplete.com/updates/

**Why Is it blocked?**:
The request is blocked by StackPath, part of the response you get:
![](https://i.imgur.com/I1RGSDz.png)

**What might unblock this?**:
I don't know :thinking:

**Comment by bnkai** [comment]
https://github.com/stashapp/CommunityScrapers/pull/117  adds Bang.com and PureTaboo scrapers since the CDP code was merged.

**Comment by bnkai** [comment]
Vixen Media Group seems to work with CDP , updated #1 with working version

**Comment by bnkai** [comment]
@halorrr  Vixen Media Group , Bang and Puretaboo scrapers using CDP were merged so they can be removed/crossed off.

**Comment by Belleyy** [comment]
**MGStage**

Sites:

- https://www.mgstage.com/

Why Is it blocked?:
You have the "Are you above 18 years old?" that block the page.

**Comment by halorrr** [comment]
@bnkai Did you ever end up revisiting the ability for the cdp scraper to inject a specific cookie? Looking at @Belleyy 's blocked scraper, it would be unblocked by creating this cookie:
![image](https://user-images.githubusercontent.com/1358708/95530499-03efbc80-09ac-11eb-9714-754783078af1.png)

The cookie isn't generated until the agree button is actually pressed so this isn't one that just clicking the scrape button twice will fix.

**Comment by bnkai** [comment]
@halorrr yeah i came to the same conclusion. It's in my todo list, i want to finish the `click` PR first and i think we might not need the cookie setting as clicking on `////a[@id="AC"]` when given a url of something like `https://www.mgstage.com/product/product_detail/326KJN-004/` seems to work. (with my PR build and a cdp test only scraper)

**Comment by bnkai** [comment]
**jacquieetmicheltv** seems to need a cookie for the disclaimer page  and/or maybe something more since cloudflare gets involved.

**Comment by Belleyy** [comment]
@halorrr You could update the main post, MGStage scraper has been created with the cookie update in stash #301

**Comment by fidofido300** [comment]
https://analized.com/ scraper broken
AnalizedNetwork.yml 
url: 
  analized.com/1/scene/

sample link
https://analized.com/trailers/

**Comment by Belleyy** [comment]
> https://analized.com/ scraper broken AnalizedNetwork.yml url: analized.com/1/scene/
> 
> sample link https://analized.com/trailers/

Did you try the latest version ? (just got updated #755 ) 
https://github.com/stashapp/CommunityScrapers/blob/master/scrapers/ThirdRockEnt.yml

**Comment by Maista6969** [comment]
Closing this as it's been unused for years
