### ISSUE TITLE
Possible to have "Unnamed" non-results marked as unmatched?

### ISSUE THREAD

**Issue by ann4belle** [stashapp/CommunityScrapers#857]
Some scrapers (for instance, ThePornDB.yml) return non-matches as "Unnamed" results with no further data. Would it be possible to correct this? I'm not familiar enough with the scraper syntax to figure this out, if it's even possible in the scraper rather than in the main app.

**Comment by bnkai** [comment]
There is a problem with how stash treats empty results vs no results. There is a somehow related open PR in the stash repo as well as an open issue <https://github.com/stashapp/stash/issues/2058> for the exact issue mentioned here. I am not sure if much can be done from the scraper part.

**Comment by bnkai** [comment]
Issue is fixed in dev build of stash. Closing this
