### ISSUE TITLE
PureTaboo Scraper

### ISSUE THREAD

**Issue by strubdog** [stashapp/CommunityScrapers#873]
Getting the following error with the PureTaboo Scraper: "exec: "google-chrome": executable file not found in %PATH%".

Thanks

**Comment by bnkai** [comment]
As mentioned in the readme 
```
Scrapers with useCDP set to true require that you have properly configured the Chrome CDP path setting in Stash
```
Thats the error you get. For puretaboo though there is an open PR with an upodated python scraper #872. I would delete PureTaboo.yml and get the scraper files from the PR

**Comment by bnkai** [comment]
The PR with the updated scraper was merged (it now requires python btw) so closing this.
