### ISSUE TITLE
indexxx.com

### ISSUE THREAD

**Issue by Alexisback** [stashapp/CommunityScrapers#882]
Can you make a scraper on this site?

https://www.indexxx.com/home

In "Stash" in the Performer cards you could load all participations in the websites 

PS: on the site it is present CloudFlare

**Comment by bnkai** [comment]
As mentioned in the channel someone tried to make a scraper but it wasnt worth the effort.
What kind of meta do you expect to get from there?
Also for scraper requests please post here https://github.com/stashapp/CommunityScrapers/issues/73
