### ISSUE TITLE
(Fixed) ThePornDB and AutoTag not pulling any data

### ISSUE THREAD

**Issue by LeGrosFromage** [stashapp/CommunityScrapers#883]
This is my first dance with Stash so very new to it - could be user error.  To get a feel on how this all works I've set up Stash (on a Linux system that has working internet access), set up one folder and put in one movie.  Stash is showing me the scenes but if I go to Edit and tell it to scrape with ThePornDB I get:
Error
scraper ThePornDB: http error 400:Bad Request

If I use AutoTag, I get:
Error
must not be null

I have Chrome and Lynx on the server and it has solid internet connectivity.  Am I doing something wrong or missing something obvious?  Again total newbie to Stash so anything's possible.

**Comment by MC1R-13** [comment]
Did you add your porndb API key at the bottom of ThePornDB scraper? And is it correct scraper? There are two for PornDB. Make sure if begins with 'The'
Autotag won't work if nothing's been scraped yet. Fixing the scraper should also fix autotag.

**Comment by LeGrosFromage** [comment]
Yeah that got it, I didn't dig into it enough to realise you had to get an API key from metadataapi.net.  The scraper appears to work although I get 0 results returned - but to be honest I think I'm just using Stash wrong, but that's another topic.

The API Key fixed the scraper error.  Thanks!

**Comment by bnkai** [comment]
From the README
```
Some scrapers support the Scrape with... function so you can you use that instead of adding a url. Scrape with... usually works with either the Title field or the filename so make sure that they provide enough data for the scraper to work with.

A Query button is also available for scrapers that support that. Clicking the button allows you to edit the text that the scraper will use for your queries.

In case of errors/no results during scraping make sure to check stash's log section (Settings->Logs->Log Level Debug) for more info.
```
ThePornDB scraper queries the `filename` when you use scrape with so if the filename is not clean enough you won't get any results. You can try the `Query` (magnifying glass) to search using a custom query https://github.com/stashapp/CommunityScrapers#scrapers

**Comment by bnkai** [comment]
Closing as the issue  seems resolved
