### ISSUE TITLE
403:Forbidden from CzechVR.com

### ISSUE THREAD

**Issue by mwtzl** [stashapp/CommunityScrapers#904]
When trying to scrape CzechVR scenes using the CzechVR.yml scraper I get a "http error 403:Forbidden" error. 

This only happens specifically with czechvr URLs, czechvrcasting and czechvrfetish ones work fine.

I have set a valid string for my Scraper User Agent.

**Comment by bnkai** [comment]
It is cloudflare detecting the scrape
As a quick and dirty (temporary) fix try editing the `CzechVR.yml` file and adding the below at the end of the file
```yaml
driver:
  useCDP: true
```

**Comment by mwtzl** [comment]
Are you sure that this is the problem, i.e., have you tried it out? I actually thought that this might be the problem and edited the scraper in that way before creating this issue.

What happens for me is that while there is no 403 error, it just loads for a few seconds without any output. CDP is configured correctly (tried with other scrapers).

**Comment by bnkai** [comment]
> Are you sure that this is the problem, i.e., have you tried it out? I actually thought that this might be the problem and edited the scraper in that way before creating this issue.
> 
> What happens for me is that while there is no 403 error, it just loads for a few seconds without any output. CDP is configured correctly (tried with other scrapers).
> 
> edit: I think what I will personally do as a workaround for now is to create a czechvrnetwork scraper for myself, since that website contains all the czechvr scenes and everything works (just like czechvrcasting and czechvrfetish using the czechvr.yml scraper)

I just tested with CDP as the only change and it works for me. The issue with cloudlfare is that it sometimes seems to detect even CDP scraping, especially if it is done via the plain path (i used the remote method with a docker container). If you are using CDP like this (file path to binary  instead of address)  you can try this method <https://github.com/stashapp/stash/wiki/FAQ#scrape-behind-paywall>

**Comment by mwtzl** [comment]
Ok, thanks. Trying the method described there still gave me an error, but it's obviously a problem on my end then, so I'll close this issue.

**Comment by poontology** [comment]
Just noticed this issue, I think they do client fingerprinting based on request headers.

If request headers don't match what client claims the User-Agent to be they give a 403. Just tested with UA being Chrome/100.0.4896.127 -> 403, Chrome/59.0.3071.115 -> 200.
I'm guessing it's the sec-ch- "client hinting" (https://wicg.github.io/ua-client-hints/) headers that they added in Chrome/89 that they check against.

Personally I just use old UA for now but this might not be sustainable in long term, at some point in future they might not believe anyone's using browser "that old" anymore.
