### ISSUE TITLE
Is it possible to scrap and create performer/uploader for PH videos

### ISSUE THREAD

**Issue by snwefly** [stashapp/CommunityScrapers#920]
Installed stash yesterday and testing  atm

Currently PH scraper able to automatically fetch url, description, upload date, cover and all the tags from properly named  videos downloaded via youtube-dl/dlp 

Manually Creating and fetching performer details via scraper is also working

Is it possible to fetch and create performer/uploader automatically for PH videos?

Thanks for your hard work 😊

**Comment by bnkai** [comment]
Performers are fetched from PH scenes. Its just that they are scraped from the `Pornstars` section of the scene(for example `https://www.pornhub.com/view_video.php?viewkey=ph6196513c77452`). We do not fetch the channel/uploader as a performer. Unless you mean something else this is covered.

**Comment by snwefly** [comment]
When you create performer, URL form able to fetech full bio and profile picture without any manual input.


worked url types

https://www.pornhub.com/model/kaya-way

https://www.pornhub.com/users/mydirtyhobby

So its possible to automatically fetch performer details.


$studio: //div[@data-type="channel"]/a   to data-type="user"

I tried to change this lines to fetch user instead of channel but so far no success, i don't know yml so i hope someone will able to do it.
